	////////////////////////TAG-E/W Units///////////////////////////////////////////////////////////
	class ADFRC_MD_Green_TAG_Base;
	class ADFRC_MD_Green_TAG_Rolled_Base;
	class ADFRC_MD_TAG_CDO_F: ADFRC_MD_Green_TAG_Rolled_Base{
		displayName="Operator";
		author="$STR_ADF_AUTHOR";
		scope=2;
		scopeCurator=2;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\Green_TAG_F.jpg";
		role="Rifleman";
		//threat[]={0.80000001,0.1,0.1}; <---For us to tweak the threat it poses to other units https://community.bistudio.com/wiki/CfgVehicles_Config_Reference#threat
		//backpack="ADFRC_Kitbag_AMCU";
		weapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		magazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		respawnMagazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		linkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class ADFRC_MD_TAG_CDO_CQB: ADFRC_MD_Green_TAG_Rolled_Base{
		displayName="Operator (CQB)";
		author="$STR_ADF_AUTHOR";
		scope=2;
		scopeCurator=2;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\Green_TAG_CQB.jpg";
		role="Rifleman";
		//threat[]={0.80000001,0.1,0.1}; <---For us to tweak the threat it poses to other units https://community.bistudio.com/wiki/CfgVehicles_Config_Reference#threat
		//backpack="ADFRC_Kitbag_AMCU";
		weapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		magazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		respawnMagazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		linkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class ADFRC_MD_TAG_CDO_TL: ADFRC_MD_Green_TAG_Rolled_Base{
		displayName="Team Leader";
		author="$STR_ADF_AUTHOR";
		scope=2;
		scopeCurator=2;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\Green_TAG_TL.jpg";
		icon="iconManLeader";
		role="Rifleman";
		cost=250000;
		//threat[]={0.80000001,0.1,0.1}; <---For us to tweak the threat it poses to other units https://community.bistudio.com/wiki/CfgVehicles_Config_Reference#threat
		//backpack="ADFRC_Kitbag_AMCU";
		weapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		magazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		respawnMagazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		linkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class ADFRC_MD_TAG_CDO_CFA: ADFRC_MD_Green_TAG_Rolled_Base{
		displayName="Combat First Aider";
		author="$STR_ADF_AUTHOR";
		scope=2;
		scopeCurator=2;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\Green_TAG_CFA.jpg";
		icon="iconManMedic";
		role="CombatLifeSaver";
		picture="pictureHeal";
		attendant=1;
		camouflage=1.6;
		//threat[]={0.80000001,0.1,0.1}; <---For us to tweak the threat it poses to other units https://community.bistudio.com/wiki/CfgVehicles_Config_Reference#threat 
		//backpack="ADFRC_Kitbag_AMCU";
		weapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		magazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		respawnMagazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		linkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class ADFRC_MD_TAG_CDO_EOD: ADFRC_MD_Green_TAG_Rolled_Base{
		displayName="Operator (EOD)";
		author="$STR_ADF_AUTHOR";
		scope=2;
		scopeCurator=2;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\Green_TAG_EOD.jpg";
		icon="iconManExplosive";
		role="Sapper";
		picture="pictureExplosive";
		cost=93000;
		camouflage=1.6;
		engineer=1;
		canDeactivateMines=1;
		detectSkill=38;
		//threat[]={0.80000001,0.1,0.1}; <---For us to tweak the threat it poses to other units https://community.bistudio.com/wiki/CfgVehicles_Config_Reference#threat
		//backpack="ADFRC_Kitbag_AMCU";
		weapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		magazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		respawnMagazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		linkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};