class CfgPatches
{
	class ADFRC_uniform_dpcu
	{
		units[]={};
		weapons[]=
		{
			"ADFRC_HelmetC_dpcu",
			"adfrc_Helmet_dpcu_canv",
			"ADFRC_booniehat_dpcu",
			"ADFRC_carrierLite_dpcu",
			"ADFRC_plateCarrier_dpcu",
			"ADFRC_tacticalVest_dpcu",
			"ADFRC_uniform_dpcu",
			"ADFRC_uniform_dpcu_recon",
			"ADFRC_uniform_dpcu_medic",
			"ADFRC_uniform_dpcu_tee",
			"ADFRC_coveralls_dpcu"
		};
		requiredVersion=0.1;
		requiredAddons[]=
		{
			"A3_Weapons_F",
			"A3_Characters_F_BLUFOR",
			"ADF_Core",
			"ADF_Weapons",
			"ADF_Gear"
		};
	};
};
class CfgEditorSubcategories
{
	class ADFRC_MEN_DPCU // Category class, you point to it in editorSubcategory property
	{
		displayName = "$STR_ADF_MEN_DPCU"; // Name visible in the list
	};
};
class cfgVehicles
{
	class ADFRC_Soldier_base_F;
	class ADFRC_DPCU_Soldier_Base: ADFRC_Soldier_base_F
	{
		scope=1;
		author="$STR_ADF_AUTHOR";
		faction="ADF";
		editorSubcategory= ADFRC_MEN_DPCU;
		genericNames="NATOMen";
		nakedUniform="U_BasicBody";
		uniformClass="ADFRC_uniform_dpcu";
		model="\A3\characters_F\BLUFOR\b_soldier_01.p3d";
		weapons[]=
		{
			"ADFRC_F88SA1_swarovski_laser",
			"ADFRC_hpII",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"ADFRC_F88SA1_swarovski_laser",
			"ADFRC_hpII",
			"Throw",
			"Put",
			"Binocular"
		};
		Items[]=
		{
			"FirstAidKit"
		};
		RespawnItems[]=
		{
			"FirstAidKit"
		};
		magazines[]=
		{
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_13Rnd_9x19_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		respawnMagazines[]=
		{
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_13Rnd_9x19_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		linkedItems[]=
		{
			"adfrc_Helmet_dpcu_canv",
			"ADFRC_carrierLite_dpcu",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"adfrc_Helmet_dpcu_canv",
			"ADFRC_carrierLite_dpcu",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class ADFRC_rifleman_dpcu: ADFRC_DPCU_Soldier_Base
	{
		scope=1;
		scopeCurator=1;
		author="$STR_ADF_AUTHOR";
		_generalMacro="ADFRC_rifleman_dpcu";
		displayName="Rifleman";
		editorPreview = "\ADF_Units\old\ADFRC_men_dpcu\preview\ADFRC_rifleman_dpcu.jpg";
		editorSubcategory= "ADFRC_MEN_DPCU";
		vehicleClass=$STR_ADF_MEN_DPCU;
		uniformAccessories[]={};
		uniformClass="ADFRC_uniform_dpcu";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"ADF_Units\old\ADFRC_men_dpcu\data\uniform_DPCU_co.paa"
		};
		backpack="adfrc_CarryAll_dpcu";
	};
	class ADFRC_engineer_dpcu: ADFRC_rifleman_dpcu
	{
		scope=1;
		scopeCurator=1;
		author="$STR_ADF_AUTHOR";
		nakedUniform="U_BasicBody";
		uniformClass="ADFRC_uniform_dpcu_new";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"ADF_Units\old\ADFRC_men_dpcu\data\uniform_DPCU_new_co.paa"
		};
		model="\A3\characters_F\BLUFOR\b_soldier_01.p3d";
		_generalMacro="ADFRC_engineer_dpcu";
		displayName="Combat Engineer";
		editorPreview = "\ADF_Units\old\ADFRC_men_dpcu\preview\ADFRC_engineer_dpcu.jpg";
		engineer=1;
		saboteur=1;
		canDeactivateMines=1;
		detectSkill=80;
		linkedItems[]=
		{
			"adfrc_Helmet_dpcu_canv",
			"ADFRC_carrierLite_dpcu",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"adfrc_Helmet_dpcu_canv",
			"ADFRC_carrierLite_dpcu",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		backpack="adfrc_CarryAll_dpcu_engineer";
		icon="iconManEngineer";
		picture="pictureRepair";
	};
	class ADFRC_grenadier_dpcu: ADFRC_rifleman_dpcu
	{
		scope=1;
		scopeCurator=1;
		author="$STR_ADF_AUTHOR";
		_generalMacro="ADFRC_grenadier_dpcu";
		displayName="Grenadier";
		editorPreview = "\ADF_Units\old\ADFRC_men_dpcu\preview\ADFRC_grenadier_dpcu.jpg";
		weapons[]=
		{
			"ADFRC_F88SA1_gl_eotech_laser",
			"ADFRC_hpII",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"ADFRC_F88SA1_gl_eotech_laser",
			"ADFRC_hpII",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_13Rnd_9x19_Mag",
			"SmokeShell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		respawnMagazines[]=
		{
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_13Rnd_9x19_Mag",
			"SmokeShell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		backpack="ADFRC_Carryall_gl_dpcu";
	};
	class ADFRC_marksman_dpcu: ADFRC_rifleman_dpcu
	{
		scope=1;
		author="$STR_ADF_AUTHOR";
		_generalMacro="ADFRC_marksman_dpcu";
		displayName="Designated Marksman";
		editorPreview = "\ADF_Units\old\ADFRC_men_dpcu\preview\ADFRC_marksman_dpcu.jpg";
		uniformClass="ADFRC_uniform_dpcu_tee";
		model="\A3\characters_F\BLUFOR\b_soldier_02.p3d";
		hiddenSelections[]=
		{
			"Camo",
			"Camo2"
		};
		hiddenSelectionsTextures[]=
		{
			"ADF_Units\old\ADFRC_men_dpcu\data\uniform_DPCU_co.paa",
			"ADF_Units\old\ADFRC_men_dpcu\data\basicbody_army_co.paa"
		};
		weapons[]=
		{
			"ADFRC_hk417_sand_army",
			"ADFRC_hpII",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"ADFRC_hk417_sand_army",
			"ADFRC_hpII",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"ADFRC_13Rnd_9x19_Mag",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE",
			"SmokeShell",
			"SmokeShell"
		};
		respawnMagazines[]=
		{
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"ADFRC_13Rnd_9x19_Mag",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE",
			"SmokeShell",
			"SmokeShell"
		};
		backpack="";
	};
	class ADFRC_medic_dpcu: ADFRC_rifleman_dpcu
	{
		scope=1;
		author="$STR_ADF_AUTHOR";
		_generalMacro="ADFRC_DPCU_Medic";
		displayName="Medical Technician";
		editorPreview = "\ADF_Units\old\ADFRC_men_dpcu\preview\ADFRC_medic_dpcu.jpg";
		attendant=1;
		model="\A3\characters_F\BLUFOR\b_soldier_03.p3d";
		uniformClass="ADFRC_uniform_dpcu_medic";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"ADF_Units\old\ADFRC_men_dpcu\data\uniform_DPCU_MEDIC_co.paa"
		};
		weapons[]=
		{
			"ADFRC_F88SA1_eotech_laser",
			"ADFRC_hpII",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"ADFRC_F88SA1_eotech_laser",
			"ADFRC_hpII",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_13Rnd_9x19_Mag",
			"SmokeShell",
			"SmokeShell",
			"SmokeShell",
			"SmokeShell"
		};
		respawnMagazines[]=
		{
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_13Rnd_9x19_Mag",
			"SmokeShell",
			"SmokeShell",
			"SmokeShell",
			"SmokeShell"
		};
		linkedItems[]=
		{
			"adfrc_Helmet_dpcu_canv",
			"ADFRC_carrierLite_dpcu",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ADFRC_HelmetC_dpcu",
			"ADFRC_carrierLite_dpcu",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		icon="iconManMedic";
		backpack="adfrc_CarryAll_dpcu_Medic";
	};
	class ADFRC_riflemanAT_dpcu: ADFRC_rifleman_dpcu
	{
		scope=1;
		author="$STR_ADF_AUTHOR";
		_generalMacro="ADFRC_DPCU_RiflemanAT";
		displayName="AT Gunner";
		editorPreview = "\ADF_Units\old\ADFRC_men_dpcu\preview\ADFRC_riflemanAT_dpcu.jpg";
		model="\A3\characters_F\BLUFOR\b_soldier_03.p3d";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"ADF_Units\old\ADFRC_men_dpcu\data\uniform_DPCU_co.paa"
		};
		weapons[]=
		{
			"ADFRC_F88SA1_swarovski_laser",
			"ADFRC_carlgustav_m3",
			"ADFRC_hpII",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"ADFRC_F88SA1_swarovski_laser",
			"ADFRC_carlgustav_m3",
			"ADFRC_hpII",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_13Rnd_9x19_Mag",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE",
			"SmokeShell",
			"SmokeShell"
		};
		respawnMagazines[]=
		{
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_13Rnd_9x19_Mag",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE",
			"SmokeShell",
			"SmokeShell"
		};
		linkedItems[]=
		{
			"adfrc_Helmet_dpcu_canv",
			"ADFRC_carrierLite_dpcu",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"adfrc_Helmet_dpcu_canv",
			"ADFRC_carrierLite_dpcu",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		icon="iconManAT";
		backpack="adfrc_CarryAll_dpcu_at";
	};
	class ADFRC_crewman_dpcu: ADFRC_rifleman_dpcu
	{
		scope=1;
		author="$STR_ADF_AUTHOR";
		_generalMacro="ADFRC_DPCU_Crewman";
		displayName="Crewman";
		editorPreview = "\ADF_Units\old\ADFRC_men_dpcu\preview\ADFRC_crewman_dpcu.jpg";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"ADF_Units\old\ADFRC_men_dpcu\data\uniform_DPCU_co.paa"
		};
		weapons[]=
		{
			"ADFRC_F88SA1_eotech_laser",
			"ADFRC_hpII",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"ADFRC_F88SA1_eotech_laser",
			"ADFRC_hpII",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_13Rnd_9x19_Mag",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE",
			"SmokeShell",
			"SmokeShell"
		};
		respawnMagazines[]=
		{
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_13Rnd_9x19_Mag",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE",
			"SmokeShell",
			"SmokeShell"
		};
		linkedItems[]=
		{
			"H_HelmetCrew_I",
			"ADFRC_carrierLite_dpcu",
			"g_combat",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"H_HelmetCrew_I",
			"ADFRC_carrierLite_dpcu",
			"g_combat",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		backpack="";
	};
	class ADFRC_cavalryman_dpcu: ADFRC_rifleman_dpcu
	{
		scope=1;
		author="$STR_ADF_AUTHOR";
		_generalMacro="ADFRC_DPCU_Crewman";
		displayName="Cavalryman";
		editorPreview = "\ADF_Units\old\ADFRC_men_dpcu\preview\ADFRC_cavalryman_dpcu.jpg";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"ADF_Units\old\ADFRC_men_dpcu\data\uniform_DPCU_co.paa"
		};
		weapons[]=
		{
			"ADFRC_F88SA1_eotech_laser",
			"ADFRC_hpII",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"ADFRC_F88SA1_eotech_laser",
			"ADFRC_hpII",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_13Rnd_9x19_Mag",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE",
			"SmokeShell",
			"SmokeShell"
		};
		respawnMagazines[]=
		{
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_13Rnd_9x19_Mag",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE",
			"SmokeShell",
			"SmokeShell"
		};
		linkedItems[]=
		{
			"H_Cap_headphones",
			"ADFRC_carrierLite_dpcu",
			"adfrc_facewear_kondor_blk_blk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"H_Cap_headphones",
			"ADFRC_carrierLite_dpcu",
			"adfrc_facewear_kondor_blk_blk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		backpack="";
	};
	class ADFRC_teamleader_dpcu: ADFRC_rifleman_dpcu
	{
		scope=1;
		author="$STR_ADF_AUTHOR";
		_generalMacro="B_Soldier_F";
		displayName="Brick Leader";
		editorPreview = "\ADF_Units\old\ADFRC_men_dpcu\preview\ADFRC_teamleader_dpcu.jpg";
		uniformClass="ADFRC_uniform_dpcu_recon";
		model="\A3\characters_F\BLUFOR\b_soldier_01.p3d";
		weapons[]=
		{
			"ADFRC_F88SA1_gl_eotech_laser",
			"ADFRC_hpII",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"ADFRC_F88SA1_gl_eotech_laser",
			"ADFRC_hpII",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_13Rnd_9x19_Mag",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE",
			"SmokeShell",
			"SmokeShell"
		};
		respawnMagazines[]=
		{
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_13Rnd_9x19_Mag",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE",
			"SmokeShell",
			"SmokeShell"
		};
		linkedItems[]=
		{
			"adfrc_Helmet_dpcu_canv",
			"ADFRC_plateCarrier_dpcu",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"adfrc_Helmet_dpcu_canv",
			"ADFRC_plateCarrier_dpcu",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		backpack="ADFRC_AssaultPack_TL_dpcu";
		icon="iconManLeader";
	};
	class ADFRC_squadleader_dpcu: ADFRC_rifleman_dpcu
	{
		scope=1;
		author="$STR_ADF_AUTHOR";
		_generalMacro="B_Soldier_F";
		displayName="Section Leader";
		editorPreview = "\ADF_Units\old\ADFRC_men_dpcu\preview\ADFRC_squadleader_dpcu.jpg";
		uniformClass="ADFRC_uniform_dpcu";
		model="\A3\characters_F\BLUFOR\b_soldier_03.p3d";
		weapons[]=
		{
			"ADFRC_F88SA1_ta648_laser",
			"ADFRC_hpII",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"ADFRC_F88SA1_ta648_laser",
			"ADFRC_hpII",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_13Rnd_9x19_Mag",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE",
			"SmokeShellPurple",
			"SmokeShellPurple",
			"SmokeShellRed",
			"SmokeShellRed",
			"SmokeShellOrange",
			"SmokeShellOrange"
		};
		respawnMagazines[]=
		{
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_13Rnd_9x19_Mag",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE",
			"SmokeShellPurple",
			"SmokeShellPurple",
			"SmokeShellRed",
			"SmokeShellRed",
			"SmokeShellOrange",
			"SmokeShellOrange"
		};
		linkedItems[]=
		{
			"adfrc_Helmet_dpcu_canv",
			"ADFRC_plateCarrier_dpcu",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"adfrc_Helmet_dpcu_canv",
			"ADFRC_plateCarrier_dpcu",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		icon="iconManOfficer";
		backpack="";
	};
	class ADFRC_pilot_dpcu: ADFRC_rifleman_dpcu
	{
		scope=1;
		author="$STR_ADF_AUTHOR";
		_generalMacro="ADFRC_DPCU_Pilot";
		displayName="Helicopter Pilot";
		editorPreview = "\ADF_Units\old\ADFRC_men_dpcu\preview\ADFRC_pilot_dpcu.jpg";
		model="\A3\Characters_F\Common\coveralls.p3d";
		uniformClass="ADFRC_coveralls_dpcu";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"ADF_Units\old\ADFRC_men_dpcu\data\pilotoveralls_DPCU_co.paa"
		};
		weapons[]=
		{
			"ADFRC_hpII",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"ADFRC_hpII",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"ADFRC_13Rnd_9x19_Mag",
			"ADFRC_13Rnd_9x19_Mag",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE",
			"SmokeShell",
			"SmokeShellRed",
			"SmokeShellPurple"
		};
		respawnMagazines[]=
		{
			"ADFRC_13Rnd_9x19_Mag",
			"ADFRC_13Rnd_9x19_Mag",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE",
			"SmokeShell",
			"SmokeShellRed",
			"SmokeShellPurple"
		};
		linkedItems[]=
		{
			"H_PilotHelmetHeli_B",
			"ADFRC_tacticalVest_dpcu",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"H_PilotHelmetHeli_B",
			"ADFRC_tacticalVest_dpcu",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		backpack="";
	};
	class ADFRC_lightGunner_dpcu: ADFRC_rifleman_dpcu
	{
		scope=1;
		author="$STR_ADF_AUTHOR";
		_generalMacro="B_Soldier_F";
		displayName="LSW Gunner";
		editorPreview = "\ADF_Units\old\ADFRC_men_dpcu\preview\ADFRC_lightGunner_dpcu.jpg";
		uniformClass="ADFRC_uniform_dpcu_recon";
		model="\A3\characters_F\BLUFOR\b_soldier_03.p3d";
		weapons[]=
		{
			"ADFRC_minimi_eotech",
			"ADFRC_hpII",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"ADFRC_minimi_eotech",
			"ADFRC_hpII",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"ADFRC_200Rnd_556_Belt_TR5",
			"ADFRC_200Rnd_556_Belt_TR5",
			"ADFRC_13Rnd_9x19_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		respawnMagazines[]=
		{
			"ADFRC_200Rnd_556_Belt_TR5",
			"ADFRC_200Rnd_556_Belt_TR5",
			"ADFRC_13Rnd_9x19_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		linkedItems[]=
		{
			"adfrc_Helmet_dpcu_canv",
			"ADFRC_carrierLite_dpcu",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ADFRC_HelmetC_dpcu",
			"ADFRC_carrierLite_dpcu",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		backpack="ADFRC_Carryall_LSW_dpcu";
		icon="iconManMG";
	};
	class ADFRC_heavyGunner_dpcu: ADFRC_rifleman_dpcu
	{
		scope=1;
		author="$STR_ADF_AUTHOR";
		_generalMacro="B_Soldier_F";
		displayName="General Support Machine Gunner";
		editorPreview = "\ADF_Units\old\ADFRC_men_dpcu\preview\ADFRC_heavyGunner_dpcu.jpg";
		uniformClass="ADFRC_uniform_dpcu";
		model="\A3\characters_F\BLUFOR\b_soldier_03.p3d";
		weapons[]=
		{
			"ADFRC_mag58_elcan",
			"ADFRC_hpII",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"ADFRC_mag58_elcan",
			"ADFRC_hpII",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"ADFRC_150Rnd_762_Belt_TR5",
			"ADFRC_13Rnd_9x19_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		respawnMagazines[]=
		{
			"ADFRC_150Rnd_762_Belt_TR5",
			"ADFRC_13Rnd_9x19_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		linkedItems[]=
		{
			"adfrc_Helmet_dpcu_canv",
			"ADFRC_carrierLite_dpcu",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"adfrc_Helmet_dpcu_canv",
			"ADFRC_carrierLite_dpcu",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		backpack="ADFRC_Carryall_MG_dpcu";
		icon="iconManMG";
	};
	class ADFRC_heavyGunner_ass_dpcu: ADFRC_rifleman_dpcu
	{
		scope=1;
		author="$STR_ADF_AUTHOR";
		_generalMacro="B_Soldier_F";
		displayName="General Support Gunner Ass.";
		editorPreview = "\ADF_Units\old\ADFRC_men_dpcu\preview\ADFRC_heavyGunner_ass_dpcu.jpg";
		uniformClass="ADFRC_uniform_dpcu_recon";
		model="\A3\characters_F\BLUFOR\b_soldier_03.p3d";
		linkedItems[]=
		{
			"adfrc_Helmet_dpcu_canv",
			"ADFRC_carrierLite_dpcu",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"adfrc_Helmet_dpcu_canv",
			"ADFRC_carrierLite_dpcu",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		backpack="ADFRC_Carryall_MG_dpcu";
		icon="iconMan";
	};
	class ADFRC_ammobearer_dpcu: ADFRC_rifleman_dpcu
	{
		scope=1;
		author="$STR_ADF_AUTHOR";
		_generalMacro="B_Soldier_F";
		displayName="Ammobearer";
		editorPreview = "ADF_Units\old\ADFRC_men_dpcu\preview\ADFRC_ammobearer_dpcu.jpg";
		uniformClass="ADFRC_uniform_dpcu_recon";
		model="\A3\characters_F\BLUFOR\b_soldier_03.p3d";
		weapons[]=
		{
			"ADFRC_F88SA1_swarovski_laser",
			"ADFRC_hpII",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"ADFRC_F88SA1_swarovski_laser",
			"ADFRC_hpII",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_13Rnd_9x19_Mag",
			"ADFRC_13Rnd_9x19_Mag",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE",
			"SmokeShell",
			"SmokeShell"
		};
		respawnMagazines[]=
		{
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_30Rnd_aug",
			"ADFRC_13Rnd_9x19_Mag",
			"ADFRC_13Rnd_9x19_Mag",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE",
			"SmokeShell",
			"SmokeShell"
		};
		linkedItems[]=
		{
			"adfrc_Helmet_dpcu_canv",
			"ADFRC_carrierLite_dpcu",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"adfrc_Helmet_dpcu_canv",
			"ADFRC_carrierLite_dpcu",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		backpack="ADFRC_Carryall_LSW_dpcu";
		icon="iconManLeader";
	};
	class B_Heli_Light_01_armed_F;
	class B_Heli_Light_01_F;
	class B_MRAP_01_F;
	class B_MRAP_01_gmg_F;
	class B_MRAP_01_hmg_F;
	class ADFRC_ah9_dpcu: B_Heli_Light_01_armed_F
	{
		scope=1;
		side=1;
		author="$STR_ADF_AUTHOR";
		faction="ADF";
		vehicleClass="AIR";
		displayName="AH-9 (DPCU)";
		editorPreview = "\ADF_Units\old\ADFRC_men_dpcu\preview\ADFRC_ah9_dpcu.jpg";
		crew="ADFRC_pilot_dpcu";
		typicalCargo[]=
		{
			"ADFRC_pilot_dpcu"
		};
		attendant=1;
		hiddenSelections[]=
		{
			"camo1"
		};
		hiddenSelectionsTextures[]=
		{
			"ADF_Units\old\ADFRC_men_dpcu\data\ah9_co.paa"
		};
	};
	class ADFRC_mh9_dpcu: B_Heli_Light_01_F
	{
		scope=1;
		side=1;
		author="$STR_ADF_AUTHOR";
		faction="ADF";
		vehicleClass="AIR";
		displayName="MH-9 (DPCU)";
		editorPreview = "\ADF_Units\old\ADFRC_men_dpcu\preview\ADFRC_mh9_dpcu.jpg";
		crew="ADFRC_pilot_dpcu";
		typicalCargo[]=
		{
			"ADFRC_teamLeader_dpcu",
			"ADFRC_rifleman_dpcu",
			"ADFRC_engineer_dpcu",
			"ADFRC_medic_dpcu",
			"ADFRC_rifleman_dpcu"
		};
		attendant=1;
		hiddenSelections[]=
		{
			"camo1"
		};
		hiddenSelectionsTextures[]=
		{
			"ADF_Units\old\ADFRC_men_dpcu\data\ah9_co.paa"
		};
	};
};
class cfgWeapons
{
	class ItemCore;
	class HeadGearItem;
	class UniformItem;
	class ItemInfo;
	class VestItem;
	class U_B_CombatUniform_mcam;
	class U_B_CombatUniform_mcam_vest;
	class U_B_CombatUniform_mcam_tee;
	class U_B_CombatUniform_mcam_worn;
	class V_RebreatherB;
	class ADFRC_uniform_dpcu: U_B_CombatUniform_mcam
	{
		scope=2;
		author="$STR_ADF_AUTHOR";
		displayName="Disruptive Pattern Combat Uniform (Long Sleeve)";
		picture="";
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="ADFRC_rifleman_dpcu";
			containerClass="Supply20";
			mass=80;
		};
	};
	class ADFRC_uniform_dpcu_new: U_B_CombatUniform_mcam
	{
		scope=2;
		author="$STR_ADF_AUTHOR";
		displayName="Disruptive Pattern Combat Uniform (Test)";
		picture="";
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="ADFRC_rifleman_dpcu_new";
			containerClass="Supply20";
			mass=80;
		};
	};
	class ADFRC_uniform_dpcu_recon: U_B_CombatUniform_mcam_vest
	{
		scope=2;
		author="$STR_ADF_AUTHOR";
		displayName="Disruptive Pattern Combat Uniform (Short Sleeve)";
		picture="";
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="ADFRC_squadleader_dpcu";
			containerClass="Supply20";
			mass=80;
		};
	};
	class ADFRC_uniform_dpcu_medic: ADFRC_uniform_dpcu
	{
		scope=2;
		author="$STR_ADF_AUTHOR";
		displayName="Disruptive Pattern Combat Uniform (Medic)";
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="ADFRC_medic_dpcu";
			containerClass="Supply20";
			mass=80;
		};
	};
	class ADFRC_uniform_dpcu_tee: ADFRC_uniform_dpcu
	{
		scope=2;
		author="$STR_ADF_AUTHOR";
		displayName="Disruptive Pattern Combat Uniform (Tee)";
		picture="";
		model="\A3\characters_F\BLUFOR\b_soldier_02.p3d";
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="ADFRC_marksman_dpcu";
			containerClass="Supply20";
			mass=80;
		};
	};
	class ADFRC_coveralls_dpcu: ADFRC_uniform_dpcu
	{
		scope=2;
		author="$STR_ADF_AUTHOR";
		displayName="Army Aviation Coveralls (DPCU)";
		model="\A3\Characters_F\Common\coveralls.p3d";
		class ItemInfo: UniformItem
		{
			uniformModel="\A3\Characters_F\Common\coveralls";
			uniformClass="ADFRC_pilot_dpcu";
			containerClass="Supply20";
			mass=80;
		};
	};
};
class CfgGroups
{
	class West
	{
		name="BLUFOR";
		side=1;
		class ADF
		{
			name="Australian Army (2000-2008)";
			class Infantry
			{
				name="Infantry";
				class ADFRC_InfSquad_DPCU
				{
					faction="ADF";
					author="$STR_ADF_AUTHOR";
					name="Rifle Section";
					side=1;
					icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
					class Unit0
					{
						side=1;
						vehicle="ADFRC_squadleader_dpcu";
						rank="CORPORAL";
						position[]={0,0,0};
					};
					class Unit1
					{
						side=1;
						vehicle="ADFRC_rifleman_dpcu";
						rank="PRIVATE";
						position[]={5,-5,0};
					};
					class Unit2
					{
						side=1;
						vehicle="ADFRC_grenadier_dpcu";
						rank="PRIVATE";
						position[]={-5,-5,0};
					};
					class Unit3
					{
						side=1;
						vehicle="ADFRC_teamleader_dpcu";
						rank="CORPORAL";
						position[]={15,-10,0};
					};
					class Unit4
					{
						side=1;
						vehicle="ADFRC_lightGunner_dpcu";
						rank="CORPORAL";
						position[]={20,-15,0};
					};
					class Unit5
					{
						side=1;
						vehicle="ADFRC_riflemanAT_dpcu";
						rank="PRIVATE";
						position[]={10,-15,0};
					};
					class Unit6
					{
						side=1;
						vehicle="ADFRC_rifleman_dpcu";
						rank="PRIVATE";
						position[]={-15,-10,0};
					};
					class Unit7
					{
						side=1;
						vehicle="ADFRC_lightGunner_dpcu";
						rank="PRIVATE";
						position[]={-20,-15,0};
					};
					class Unit8
					{
						side=1;
						vehicle="ADFRC_riflemanAT_dpcu";
						rank="PRIVATE";
						position[]={-10,-15,0};
					};
				};
				class ADFRC_InfTeam_DPCU
				{
					faction="ADFU";
					author="$STR_ADF_AUTHOR";
					name="Fire Team";
					side=1;
					icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
					class Unit0
					{
						side=1;
						vehicle="ADFRC_teamleader_dpcu";
						rank="SERGEANT";
						position[]={0,0,0};
					};
					class Unit1
					{
						side=1;
						vehicle="ADFRC_lightGunner_dpcu";
						rank="CORPORAL";
						position[]={5,-5,0};
					};
					class Unit2
					{
						side=1;
						vehicle="ADFRC_grenadier_dpcu";
						rank="PRIVATE";
						position[]={-5,-5,0};
					};
					class Unit3
					{
						side=1;
						vehicle="ADFRC_ammobearer_dpcu";
						rank="PRIVATE";
						position[]={10,-10,0};
					};
				};
				class ADFRC_ReconSquad_DPCU
				{
					faction="ADF";
					side=1;
					author="$STR_ADF_AUTHOR";
					name="Cavalry Foot Patrol";
					icon = "\A3\ui_f\data\map\markers\nato\b_recon.paa";
					class Unit0
					{
						position[]={0,0,0};
						rank="SERGEANT";
						side=1;
						vehicle="ADFRC_teamleader_dpcu";
					};
					class Unit1
					{
						position[]={5,-5,0};
						rank="PRIVATE";
						side=1;
						vehicle="ADFRC_cavalryman_dpcu";
					};
					class Unit2
					{
						position[]={-5,-5,0};
						rank="PRIVATE";
						side=1;
						vehicle="ADFRC_cavalryman_dpcu";
					};
					class Unit3
					{
						position[]={10,-10,0};
						rank="CORPORAL";
						side=1;
						vehicle="ADFRC_marksman_dpcu";
					};
				};
				class ADFRC_InfAssault_DPCU
				{
					faction="ADFU";
					side=1;
					author="$STR_ADF_AUTHOR";
					name="Manoeuvre Support Section";
					icon = "\A3\ui_f\data\map\markers\nato\b_support.paa";
					class Unit0
					{
						side=1;
						vehicle="ADFRC_squadleader_dpcu";
						rank="LIEUTENANT";
						position[]={0,0,0};
					};
					class Unit1
					{
						side=1;
						vehicle="ADFRC_heavyGunner_dpcu";
						rank="CORPORAL";
						position[]={5,-5,0};
					};
					class Unit2
					{
						side=1;
						vehicle="ADFRC_heavyGunner_ass_dpcu";
						rank="PRIVATE";
						position[]={0,-5,0};
					};
					class Unit3
					{
						side=1;
						vehicle="ADFRC_medic_dpcu";
						rank="PRIVATE";
						position[]={-5,-5,0};
					};
					class Unit4
					{
						side=1;
						vehicle="ADFRC_teamleader_dpcu";
						rank="SERGEANT";
						position[]={-15,-10,0};
					};
					class Unit5
					{
						side=1;
						vehicle="ADFRC_heavyGunner_dpcu";
						rank="PRIVATE";
						position[]={-10,-15,0};
					};
					class Unit6
					{
						side=1;
						vehicle="ADFRC_heavyGunner_ass_dpcu";
						rank="PRIVATE";
						position[]={-15,-15,0};
					};
					class Unit7
					{
						side=1;
						vehicle="ADFRC_riflemanAT_dpcu";
						rank="PRIVATE";
						position[]={-20,-15,0};
					};
					class Unit8
					{
						side=1;
						vehicle="ADFRC_teamleader_dpcu";
						rank="SERGEANT";
						position[]={15,-10,0};
					};
					class Unit9
					{
						side=1;
						vehicle="ADFRC_heavyGunner_dpcu";
						rank="PRIVATE";
						position[]={10,-15,0};
					};
					class Unit10
					{
						side=1;
						vehicle="ADFRC_heavyGunner_ass_dpcu";
						rank="PRIVATE";
						position[]={15,-15,0};
					};
					class Unit11
					{
						side=1;
						vehicle="ADFRC_riflemanAT_dpcu";
						rank="PRIVATE";
						position[]={20,-15,0};
					};
				};
				class ADFRC_InfSentry_DPCU
				{
					faction="ADF";
					author="$STR_ADF_AUTHOR";
					name="Sentry";
					side=1;
					icon = "\A3\ui_f\data\map\markers\nato\b_support.paa";
					class Unit0
					{
						side=1;
						vehicle="ADFRC_grenadier_dpcu";
						rank="PRIVATE";
						position[]={0,0,0};
					};
					class Unit1
					{
						side=1;
						vehicle="ADFRC_riflemanAT_dpcu";
						rank="PRIVATE";
						position[]={5,-5,0};
					};
				};
			};
			class Motorized
			{
				name="Motorized";
				class ADFRC_MotInf_Team_DPCU_Bush
				{
					faction="ADFU";
					author="$STR_ADF_AUTHOR";
					name="Bushmaster Section";
					side=1;
					icon = "\A3\ui_f\data\map\markers\nato\b_motor_inf.paa";
					class Unit0
					{
						position[]={0,-5,0};
						rank="LIEUTENANT";
						side=1;
						Vehicle="ADFRC_squadleader_dpcu";
					};
					class Unit1
					{
						position[]={5,-10,0};
						rank="SERGEANT";
						side=1;
						Vehicle="ADFRC_teamleader_dpcu";
					};
					class Unit2
					{
						position[]={-5,-10,0};
						rank="CORPORAL";
						side=1;
						Vehicle="ADFRC_medic_dpcu";
					};
					class Unit3
					{
						position[]={10,-15,0};
						rank="PRIVATE";
						side=1;
						Vehicle="ADFRC_grenadier_dpcu";
					};
					class Unit4
					{
						position[]={-10,-15,0};
						rank="PRIVATE";
						side=1;
						Vehicle="ADFRC_lightGunner_dpcu";
					};
					class Unit5
					{
						position[]={15,-20,0};
						rank="PRIVATE";
						side=1;
						Vehicle="ADFRC_riflemanAT_dpcu";
					};
					class Unit6
					{
						position[]={0,0,0};
						rank="PRIVATE";
						side=1;
						Vehicle="ADFRC_bushmaster_pws127mm_F";
					};
				};
				class ADFRC_MotInf_Reinforcements_DPCU
				{
					faction="ADF";
					author="$STR_ADF_AUTHOR";
					name="Motorised Reinforcements";
					side=1;
					icon = "\A3\ui_f\data\map\markers\nato\b_motor_inf.paa";
					class Unit0
					{
						position[]={0,0,0};
						rank="SERGEANT";
						side=1;
						Vehicle="ADFRC_hemtt_transport";
					};
					class Unit1
					{
						position[]={0,-5,0};
						rank="SERGEANT";
						side=1;
						Vehicle="ADFRC_squadleader_dpcu";
					};
					class Unit2
					{
						position[]={5,10,0};
						rank="CORPORAL";
						side=1;
						Vehicle="ADFRC_medic_dpcu";
					};
					class Unit3
					{
						position[]={-10,-10,0};
						rank="PRIVATE";
						side=1;
						Vehicle="ADFRC_grenadier_dpcu";
					};
					class Unit4
					{
						position[]={20,20,0};
						rank="PRIVATE";
						side=1;
						Vehicle="ADFRC_riflemanAT_dpcu";
					};
					class Unit5
					{
						position[]={-20,-20,0};
						rank="PRIVATE";
						side=1;
						Vehicle="ADFRC_hemtt_transport";
					};
				};
			};
			class Mechanized
			{
				name="Mechanized (ASLAV)";
				class ADFRC_MechInfSquad_DPCU_ASLAV
				{
					faction="ADFU";
					author="$STR_ADF_AUTHOR";
					name="ASLAV Cavalry Section";
					side=1;
					icon = "\A3\ui_f\data\map\markers\nato\b_mech_inf.paa";
					class Unit0
					{
						position[]={0,5,0};
						rank="PRIVATE";
						side=1;
						Vehicle="ADFRC_aslav";
					};
					class Unit1
					{
						position[]={0,-5,0};
						rank="SERGEANT";
						side=1;
						Vehicle="ADFRC_teamleader_dpcu";
					};
					class Unit2
					{
						position[]={5,-10,0};
						rank="CORPORAL";
						side=1;
						Vehicle="ADFRC_cavalryman_dpcu";
					};
					class Unit3
					{
						position[]={-5,-10,0};
						rank="CORPORAL";
						side=1;
						Vehicle="ADFRC_cavalryman_dpcu";
					};
					class Unit4
					{
						position[]={0,-10,0};
						rank="CORPORAL";
						side=1;
						Vehicle="ADFRC_marksman_dpcu";
					};
					
				};
			};
		};
	};
};