dir = "@ADFRecut";
name = "ADF Re-Cut 0.0.9";
actionName = "Website";
action = "https://discord.gg/sNKr7fwHUr";
logo = "mod.paa";
logoOver = "mod_g.paa";
tooltip = "ADF Re-Cut 0.0.9";
tooltipOwned = "ADF Recut Addons Owned";
overview = "ADF: Re-Cut is the continuation of the old ADFU mod.";
author = "ADF Re-Cut Team | ADFUncut Mod Team";
overviewPicture = "mod.paa";
overviewText = "ADF: Re-Cut is the continuation of the old ADFU mod.";
overviewFootnote = "<br /><t color='#999999'>ADF Uncut<t />";
version = "0.0.9";