	class ADFRC_MD_AMCU_Soldier_Base;
	class ADFRC_MD_AMCU_Soldier_Rolled_Base;
	class ADFRC_MD_AMCU_Soldier_Tee_Base;
	////////////////////////Regular Units///////////////////////////////////////////////////////////
	class ADFRC_MD_AMCU_Soldier_F: ADFRC_MD_AMCU_Soldier_Base{
		displayName="Rifleman";
		author="$STR_ADF_AUTHOR";
		scope=2;
		scopeCurator=2;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\AMCU_Soldier_F.jpg";
		role="Rifleman";
		//threat[]={0.80000001,0.1,0.1}; <---For us to tweak the threat it poses to other units https://community.bistudio.com/wiki/CfgVehicles_Config_Reference#threat 
		weapons[]={
			"arifle_AUG_black_arco_flash_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"arifle_AUG_black_arco_flash_F",
			"Throw",
			"Put"
		};
		magazines[]={
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_mixed_ef88",
			"ADFRC_30Rnd_aug_mixed_ef88",
			"ADFRC_30Rnd_aug_TR_ef88",
			"ADFRC_30Rnd_aug_TR_ef88",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		respawnMagazines[]={
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_mixed_ef88",
			"ADFRC_30Rnd_aug_mixed_ef88",
			"ADFRC_30Rnd_aug_TR_ef88",
			"ADFRC_30Rnd_aug_TR_ef88",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		items[] = {"FirstAidKit", "FirstAidKit", "FirstAidKit",};
		linkedItems[]={
			"adfrc_teamwendy_exfil_amcu_ct_Aus",
			"ADFRC_TBAS_T2_Rifleman",
			"adfrc_facewear_gatorz_1",
			"adfrc_l3h_psq36",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_TBAS_T2_Rifleman",
			"adfrc_facewear_ESS_1",
			"adfrc_l3h_psq36",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	
class ADFRC_MD_AMCU_Soldier_Light: ADFRC_MD_AMCU_Soldier_Base{
		displayName="Rifleman (Light)";
		author="$STR_ADF_AUTHOR";
		scope=2;
		scopeCurator=2;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\AMCU_Soldier_F.jpg";
		role="Rifleman";
		//threat[]={0.80000001,0.1,0.1}; <---For us to tweak the threat it poses to other units https://community.bistudio.com/wiki/CfgVehicles_Config_Reference#threat 
		//backpack="ADFRC_AssaultPack_AMCU";
		weapons[]={
			"ADFRC_EF88_Minimil_Base",
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"ADFRC_EF88_Minimil_Base",
			"Throw",
			"Put"
		};
		magazines[]={
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88"
		};
		respawnMagazines[]={
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88"
		};
		items[] = {"FirstAidKit"};
		linkedItems[]={
			"adfrc_teamwendy_exfil_amcu_ct_Aus",
			"ADFRC_TBAS_T2_Rifleman_Light",
			"adfrc_facewear_kondor_blk_blk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_TBAS_T2_Rifleman_Light",
			"adfrc_facewear_kondor_blk_blk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	
class ADFRC_MD_AMCU_Soldier_Sidearm: ADFRC_MD_AMCU_Soldier_Base{
		displayName="Rifleman (Sidearm)";
		author="$STR_ADF_AUTHOR";
		scope=2;
		scopeCurator=2;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\AMCU_Soldier_F.jpg";
		role="Rifleman";
		//threat[]={0.80000001,0.1,0.1}; <---For us to tweak the threat it poses to other units https://community.bistudio.com/wiki/CfgVehicles_Config_Reference#threat 
		backpack="ADFRC_BP_Placeholder_AMCU_1";
		weapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		magazines[]={
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_mixed_ef88",
			"ADFRC_30Rnd_aug_mixed_ef88",
			"ADFRC_30Rnd_aug_TR_ef88",
			"ADFRC_30Rnd_aug_TR_ef88",
			"ADFRC_13Rnd_9x19_Mag",
			"ADFRC_13Rnd_9x19_Mag",
			"ADFRC_13Rnd_9x19_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		respawnMagazines[]={
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_mixed_ef88",
			"ADFRC_30Rnd_aug_mixed_ef88",
			"ADFRC_30Rnd_aug_TR_ef88",
			"ADFRC_30Rnd_aug_TR_ef88",
			"ADFRC_13Rnd_9x19_Mag",
			"ADFRC_13Rnd_9x19_Mag",
			"ADFRC_13Rnd_9x19_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		items[] = {"FirstAidKit", "FirstAidKit", "FirstAidKit", "FirstAidKit", "FirstAidKit"};
		linkedItems[]={
			"adfrc_teamwendy_exfil_amcu_ct_Aus",
			"ADFRC_TBAS_T2_Rifleman_Pistol",
			"adfrc_facewear_Balaclava_amc_1",
			"adfrc_l3h_psq36",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_TBAS_T2_Rifleman_Pistol",
			"adfrc_facewear_Balaclava_amc_1",
			"adfrc_l3h_psq36",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	
	
	class ADFRC_MD_AMCU_Soldier_Grenadier: ADFRC_MD_AMCU_Soldier_Base{
		displayName="Grenadier";
		author="$STR_ADF_AUTHOR";
		scope=2;
		scopeCurator=2;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\AMCU_Soldier_Grenadier.jpg";
		role="Grenadier";
		cost=200000;
		//threat[]={0.80000001,0.1,0.1}; <---For us to tweak the threat it poses to other units https://community.bistudio.com/wiki/CfgVehicles_Config_Reference#threat 
		backpack="ADFRC_BP_Assault_AMCU_1";
		weapons[]={
			"arifle_AUG_GL_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"arifle_AUG_GL_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		magazines[]={
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_mixed_ef88",
			"ADFRC_30Rnd_aug_mixed_ef88",
			"ADFRC_13Rnd_9x19_Mag",
			"ADFRC_13Rnd_9x19_Mag",
			"ADFRC_13Rnd_9x19_Mag",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell", 
			"UGL_FlareWhite_F", 
			"1Rnd_SmokeRed_Grenade_shell", 
			"1Rnd_SmokeBlue_Grenade_shell",
			"SmokeShell",
			"SmokeShell",
		};
		respawnMagazines[]={
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_mixed_ef88",
			"ADFRC_30Rnd_aug_mixed_ef88",
			"ADFRC_13Rnd_9x19_Mag",
			"ADFRC_13Rnd_9x19_Mag",
			"ADFRC_13Rnd_9x19_Mag",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell", 
			"UGL_FlareWhite_F", 
			"1Rnd_SmokeRed_Grenade_shell", 
			"1Rnd_SmokeBlue_Grenade_shell",
			"SmokeShell",
			"SmokeShell",
		};
		items[] = {"FirstAidKit", "FirstAidKit", "FirstAidKit"};
		linkedItems[]={
			"adfrc_teamwendy_exfil_amcu_ct_Aus",
			"ADFRC_TBAS_T2_Gren",
			"adfrc_facewear_ESS_1",
			"adfrc_l3h_psq36",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"adfrc_teamwendy_exfil_amcu_ct_Aus",
			"ADFRC_TBAS_T2_Gren",
			"adfrc_facewear_ESS_1",
			"adfrc_l3h_psq36",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class ADFRC_MD_AMCU_Soldier_LMG: ADFRC_MD_AMCU_Soldier_Rolled_Base{ // Rolled Sleeves
		displayName="LSW Gunner (Minimi)";
		author="$STR_ADF_AUTHOR";
		scope=2;
		scopeCurator=2;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\AMCU_Soldier_LMG.jpg";
		class SpeechVariants{
			class Default{
				speechSingular[]={
					"veh_infantry_MG_s"
				};
				speechPlural[]={
					"veh_infantry_MG_p"
				};
			};
		};
		textSingular="$STR_A3_nameSound_veh_infantry_MG_s";
		textPlural="$STR_A3_nameSound_veh_infantry_MG_p";
		nameSound="veh_infantry_MG_s";
		icon="iconManMG";
		role="MachineGunner";
		cost=220000;
		//threat[]={0.80000001,0.1,0.1}; <---For us to tweak the threat it poses to other units https://community.bistudio.com/wiki/CfgVehicles_Config_Reference#threat 
		weapons[]={
			"ADFRC_minimi",
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"ADFRC_minimi",
			"Throw",
			"Put"
		};
		magazines[]={
			"ADFRC_200Rnd_556_Belt_TR",
			"ADFRC_200Rnd_556_Belt_TR5",
			"ADFRC_100Rnd_556_Belt_TR5",
			"ADFRC_100Rnd_556_Belt_TR5",
			"ADFRC_100Rnd_556_Belt",
			"ADFRC_100Rnd_556_Belt",
			"SmokeShell",
			"Chemlight_blue",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		respawnMagazines[]={
			"ADFRC_200Rnd_556_Belt_TR",
			"ADFRC_200Rnd_556_Belt_TR5",
			"ADFRC_100Rnd_556_Belt_TR5",
			"ADFRC_100Rnd_556_Belt_TR5",
			"ADFRC_100Rnd_556_Belt",
			"ADFRC_100Rnd_556_Belt",
			"SmokeShell",
			"Chemlight_blue",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		items[] = {"FirstAidKit", "FirstAidKit", "FirstAidKit"};
		linkedItems[]={
			"adfrc_teamwendy_exfil_amcu_ct_Aus",
			"ADFRC_TBAS_T2_LMG",
			"adfrc_facewear_kondor_blk_blk",
			"adfrc_l3h_psq36",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"adfrc_teamwendy_exfil_amcu_ct_Aus",
			"ADFRC_TBAS_T2_LMG",
			"adfrc_facewear_kondor_blk_blk",
			"adfrc_l3h_psq36",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		backpack="ADFRC_BP_Assault_AMCU_1";
		
	};
	class ADFRC_MD_AMCU_Soldier_MMG: ADFRC_MD_AMCU_Soldier_Rolled_Base{ // Rolled Sleeves
		displayName="LSW Gunner (Maximi)";
		author="$STR_ADF_AUTHOR";
		scope=2;
		scopeCurator=2;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\AMCU_Soldier_MMG.jpg";
		class SpeechVariants{
			class Default{
				speechSingular[]={
					"veh_infantry_MG_s"
				};
				speechPlural[]={
					"veh_infantry_MG_p"
				};
			};
		};
		textSingular="$STR_A3_nameSound_veh_infantry_MG_s";
		textPlural="$STR_A3_nameSound_veh_infantry_MG_p";
		nameSound="veh_infantry_MG_s";
		icon="iconManMG";
		role="MachineGunner";
		cost=220000;
		//threat[]={0.80000001,0.1,0.1}; <---For us to tweak the threat it poses to other units https://community.bistudio.com/wiki/CfgVehicles_Config_Reference#threat 
		weapons[]={
			"ADFRC_maximi",
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"ADFRC_maximi",
			"Throw",
			"Put"
		};
		magazines[]={
			"ADFRC_50Rnd_762_Belt_TR5",
			"ADFRC_F1_Grenade",
			"ADFRC_F1_Grenade",
			"SmokeShell",
			"Chemlight_blue",
			"Chemlight_blue",
			"ADFRC_150Rnd_762_Belt_TR5",
			"ADFRC_100Rnd_762_Belt",
			"ADFRC_50Rnd_762_Belt_TR",
			"ADFRC_50Rnd_762_Belt_TR5",
			"ADFRC_50Rnd_762_Belt_TR5",
			"ADFRC_50Rnd_762_Belt_TR5",
			"ADFRC_100_Rnd_762_Belt_TR5"
		};
		respawnMagazines[]={
			"ADFRC_50Rnd_762_Belt_TR5",
			"ADFRC_F1_Grenade",
			"ADFRC_F1_Grenade",
			"SmokeShell",
			"Chemlight_blue",
			"Chemlight_blue",
			"ADFRC_150Rnd_762_Belt_TR5",
			"ADFRC_100Rnd_762_Belt",
			"ADFRC_50Rnd_762_Belt_TR",
			"ADFRC_50Rnd_762_Belt_TR5",
			"ADFRC_50Rnd_762_Belt_TR5",
			"ADFRC_50Rnd_762_Belt_TR5",
			"ADFRC_100_Rnd_762_Belt_TR5"
		};
		items[] = {"FirstAidKit", "FirstAidKit", "FirstAidKit"};
		linkedItems[]={
			"adfrc_teamwendy_exfil_amcu_ct_Aus",
			"ADFRC_TBAS_T2_LMG",
			"adfrc_facewear_kondor_blk_blk",
			"adfrc_l3h_psq36",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"adfrc_teamwendy_exfil_amcu_ct_Aus",
			"ADFRC_TBAS_T2_LMG",
			"adfrc_facewear_kondor_blk_blk",
			"adfrc_l3h_psq36",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class ADFRC_MD_AMCU_Soldier_GSMG: ADFRC_MD_AMCU_Soldier_Rolled_Base{ // Rolled Sleeves
		displayName="General Support Machine Gunner";
		author="$STR_ADF_AUTHOR";
		scope=2;
		scopeCurator=2;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\AMCU_Soldier_GSMG.jpg";
		class SpeechVariants{
			class Default{
				speechSingular[]={
					"veh_infantry_MG_s"
				};
				speechPlural[]={
					"veh_infantry_MG_p"
				};
			};
		};
		textSingular="$STR_A3_nameSound_veh_infantry_MG_s";
		textPlural="$STR_A3_nameSound_veh_infantry_MG_p";
		nameSound="veh_infantry_MG_s";
		icon="iconManMG";
		role="MachineGunner";
		cost=220000;
		//threat[]={0.80000001,0.1,0.1}; <---For us to tweak the threat it poses to other units https://community.bistudio.com/wiki/CfgVehicles_Config_Reference#threat 
		backpack="ADFRC_BP_Placeholder_AMCU_1";
		weapons[]={
			"adfrc_mag58",
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"adfrc_mag58",
			"Throw",
			"Put"
		};
		magazines[]={
			"ADFRC_50Rnd_762_Belt_TR5",
			"ADFRC_F1_Grenade",
			"ADFRC_F1_Grenade",
			"SmokeShell",
			"Chemlight_blue",
			"Chemlight_blue",
			"ADFRC_150Rnd_762_Belt_TR5",
			"ADFRC_100Rnd_762_Belt",
			"ADFRC_50Rnd_762_Belt_TR",
			"ADFRC_50Rnd_762_Belt_TR5",
			"ADFRC_50Rnd_762_Belt_TR5",
			"ADFRC_50Rnd_762_Belt_TR5",
			"ADFRC_50Rnd_762_Belt_TR5",
			"ADFRC_100_Rnd_762_Belt_TR5"
		};
		respawnMagazines[]={
			"ADFRC_50Rnd_762_Belt_TR5",
			"ADFRC_F1_Grenade",
			"ADFRC_F1_Grenade",
			"SmokeShell",
			"Chemlight_blue",
			"Chemlight_blue",
			"ADFRC_150Rnd_762_Belt_TR5",
			"ADFRC_100Rnd_762_Belt",
			"ADFRC_50Rnd_762_Belt_TR",
			"ADFRC_50Rnd_762_Belt_TR5",
			"ADFRC_50Rnd_762_Belt_TR5",
			"ADFRC_50Rnd_762_Belt_TR5",
			"ADFRC_50Rnd_762_Belt_TR5",
			"ADFRC_100_Rnd_762_Belt_TR5"
		};
		linkedItems[]={
			"ADFRC_TBAS_T2_LMG",
			"adfrc_teamwendy_exfil_amcu_ct_Aus",
			"adfrc_facewear_kondor_blk_blk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"adfrc_l3h_psq36"
		};
		respawnLinkedItems[]={
			"ADFRC_TBAS_T2_LMG",
			"adfrc_teamwendy_exfil_amcu_ct_Aus",
			"adfrc_facewear_kondor_blk_blk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"adfrc_l3h_psq36"
		};
	};
	class ADFRC_MD_AMCU_Soldier_Officer: ADFRC_MD_AMCU_Soldier_Base{
		displayName="Officer";
		author="$STR_ADF_AUTHOR";
		scope=2;
		scopeCurator=2;	
		editorPreview = "\ADF_Units\data\editorPreviews\MD\AMCU_Soldier_Officer.jpg";
		icon="iconManOfficer";
		role="Rifleman";
		cost=250000;
		camouflage=1.6;
		//threat[]={0.80000001,0.1,0.1}; <---For us to tweak the threat it poses to other units https://community.bistudio.com/wiki/CfgVehicles_Config_Reference#threat 
		backpack="adfrc_molle_bag_ASIP";
		weapons[]={
			"ADFRC_EF88_Minimil_c_Base",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"ADFRC_EF88_Minimil_c_Base",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		magazines[]={
			"ADFRC_13Rnd_9x19_Mag",
			"ADFRC_13Rnd_9x19_Mag",
			"ADFRC_F1_Grenade",
			"ADFRC_F1_Grenade",
			"SmokeShell",
			"Chemlight_blue",
			"Chemlight_blue",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
		};
		respawnMagazines[]={
			"ADFRC_13Rnd_9x19_Mag",
			"ADFRC_13Rnd_9x19_Mag",
			"ADFRC_F1_Grenade",
			"ADFRC_F1_Grenade",
			"SmokeShell",
			"Chemlight_blue",
			"Chemlight_blue",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
		};
		items[] = {"FirstAidKit"};
		linkedItems[]={
			"adfrc_teamwendy_exfil_amcu_Aus",
			"ADFRC_TBAS_T2_Officer",
			"adfrc_facewear_ESS_1",
			"adfrc_l3h_psq36",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"adfrc_teamwendy_exfil_amcu_Aus",
			"ADFRC_TBAS_T2_Officer",
			"adfrc_facewear_ESS_1",
			"adfrc_l3h_psq36",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class ADFRC_MD_AMCU_Soldier_SectionComm: ADFRC_MD_AMCU_Soldier_Rolled_Base{ // Rolled Sleeves
		displayName="Section Commander";
		author="$STR_ADF_AUTHOR";
		scope=2;
		scopeCurator=2;	
		editorPreview = "\ADF_Units\data\editorPreviews\MD\AMCU_Soldier_SectionComm.jpg";
		icon="iconManLeader";
		role="Rifleman";
		cost=250000;
		camouflage=1.4;
		//threat[]={0.80000001,0.1,0.1}; <---For us to tweak the threat it poses to other units https://community.bistudio.com/wiki/CfgVehicles_Config_Reference#threat 
		backpack="adfrc_molle_bag_ASIP";
		weapons[]={
			"arifle_AUG_black_MRCO_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"arifle_AUG_black_MRCO_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		magazines[]={
			"ADFRC_13Rnd_9x19_Mag",
			"ADFRC_13Rnd_9x19_Mag",
			"ADFRC_F1_Grenade",
			"SmokeShell",
			"Chemlight_blue",
			"Chemlight_blue",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_TR_ef88",
			"ADFRC_30Rnd_aug_TR_ef88",
			"ADFRC_30Rnd_aug_TR_ef88",
			"ADFRC_30Rnd_aug_TR_ef88",
			"ADFRC_30Rnd_aug_TR_ef88",
			"ADFRC_30Rnd_aug_TR_ef88",
			"SmokeShellYellow", 
			"SmokeShellRed", 
			"SmokeShellRed", 
			"SmokeShellPurple", 
			"SmokeShellBlue", 
			"SmokeShellBlue", 
			"B_IR_Grenade", 
		};
		respawnMagazines[]={
			"ADFRC_13Rnd_9x19_Mag",
			"ADFRC_13Rnd_9x19_Mag",
			"ADFRC_F1_Grenade",
			"SmokeShell",
			"Chemlight_blue",
			"Chemlight_blue",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_TR_ef88",
			"ADFRC_30Rnd_aug_TR_ef88",
			"ADFRC_30Rnd_aug_TR_ef88",
			"ADFRC_30Rnd_aug_TR_ef88",
			"ADFRC_30Rnd_aug_TR_ef88",
			"ADFRC_30Rnd_aug_TR_ef88",
			"SmokeShellYellow", 
			"SmokeShellRed", 
			"SmokeShellRed", 
			"SmokeShellPurple", 
			"SmokeShellBlue", 
			"SmokeShellBlue", 
			"B_IR_Grenade", 
		};
		items[] = {"FirstAidKit", "FirstAidKit", "FirstAidKit", "FirstAidKit"};
		linkedItems[]={
			"adfrc_teamwendy_exfil_amcu_ct_Aus",
			"ADFRC_TBAS_T2_SECO",
			"adfrc_facewear_Balaclava_amc_1",
			"adfrc_l3h_psq36",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"adfrc_teamwendy_exfil_amcu_ct_Aus",
			"ADFRC_TBAS_T2_SECO",
			"adfrc_facewear_Balaclava_amc_1",
			"adfrc_l3h_psq36",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class ADFRC_MD_AMCU_Soldier_BrickComm: ADFRC_MD_AMCU_Soldier_Base{
		displayName="Brick Leader";
		author="$STR_ADF_AUTHOR";
		scope=2;
		scopeCurator=2;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\AMCU_Soldier_BrickComm.jpg";
		icon="iconManLeader";
		role="Rifleman";
		cost=250000;
		camouflage=1.4;
		//threat[]={0.80000001,0.1,0.1}; <---For us to tweak the threat it poses to other units https://community.bistudio.com/wiki/CfgVehicles_Config_Reference#threat 
		backpack="ADFRC_BP_Assault_AMCU_1";
		weapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		magazines[]={
			"ADFRC_13Rnd_9x19_Mag",
			"ADFRC_13Rnd_9x19_Mag",
			"ADFRC_F1_Grenade",
			"ADFRC_F1_Grenade",
			"ADFRC_F1_Grenade",
			"SmokeShell",
			"Chemlight_blue",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_TR_ef88",
			"ADFRC_30Rnd_aug_TR_ef88",
			"ADFRC_30Rnd_aug_TR_ef88",
			"ADFRC_30Rnd_aug_TR_ef88",
			"ADFRC_30Rnd_aug_TR_ef88",
			"ADFRC_30Rnd_aug_TR_ef88",
			"SmokeShellRed", 
			"SmokeShellPurple", 
			"SmokeShellBlue", 
		};
		respawnMagazines[]={
			"ADFRC_13Rnd_9x19_Mag",
			"ADFRC_13Rnd_9x19_Mag",
			"ADFRC_F1_Grenade",
			"ADFRC_F1_Grenade",
			"ADFRC_F1_Grenade",
			"SmokeShell",
			"Chemlight_blue",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_TR_ef88",
			"ADFRC_30Rnd_aug_TR_ef88",
			"ADFRC_30Rnd_aug_TR_ef88",
			"ADFRC_30Rnd_aug_TR_ef88",
			"ADFRC_30Rnd_aug_TR_ef88",
			"ADFRC_30Rnd_aug_TR_ef88",
			"SmokeShellRed", 
			"SmokeShellPurple", 
			"SmokeShellBlue", 
		};
		items[] = {"FirstAidKit", "FirstAidKit", "FirstAidKit", "FirstAidKit"};
		linkedItems[]={
			"adfrc_teamwendy_exfil_amcu_ct_Aus",
			"ADFRC_TBAS_T2_TL",
			"adfrc_facewear_Balaclava_olv_2",
			"adfrc_l3h_psq36",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"adfrc_teamwendy_exfil_amcu_ct_Aus",
			"ADFRC_TBAS_T2_TL",
			"adfrc_facewear_Balaclava_olv_2",
			"adfrc_l3h_psq36",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	
	class ADFRC_MD_AMCU_Soldier_Marksman: ADFRC_MD_AMCU_Soldier_Base{
		displayName="Designated Marksman";
		author="$STR_ADF_AUTHOR";
		scope=2;
		scopeCurator=2;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\AMCU_Soldier_Marksman.jpg";
		class SpeechVariants{
			class Default{
				speechSingular[]={
					"veh_infantry_sniper_s"
				};
				speechPlural[]={
					"veh_infantry_sniper_p"
				};
			};
		};
		textSingular="$STR_A3_nameSound_veh_infantry_sniper_s";
		textPlural="$STR_A3_nameSound_veh_infantry_sniper_p";
		nameSound="veh_infantry_sniper_s";
		role="Marksman";
		cost=250000;
		//threat[]={0.80000001,0.1,0.1}; <---For us to tweak the threat it poses to other units https://community.bistudio.com/wiki/CfgVehicles_Config_Reference#threat 
		backpack="ADFRC_BP_Placeholder_AMCU_1";
		weapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		magazines[]={
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_mixed_ef88",
			"ADFRC_30Rnd_aug_mixed_ef88",
			"ADFRC_30Rnd_aug_TR_ef88",
			"ADFRC_30Rnd_aug_TR_ef88",
			"ADFRC_13Rnd_9x19_Mag",
			"ADFRC_13Rnd_9x19_Mag",
			"ADFRC_13Rnd_9x19_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		respawnMagazines[]={
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_mixed_ef88",
			"ADFRC_30Rnd_aug_mixed_ef88",
			"ADFRC_30Rnd_aug_TR_ef88",
			"ADFRC_30Rnd_aug_TR_ef88",
			"ADFRC_13Rnd_9x19_Mag",
			"ADFRC_13Rnd_9x19_Mag",
			"ADFRC_13Rnd_9x19_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		items[] = {"FirstAidKit", "FirstAidKit", "FirstAidKit", "FirstAidKit", "FirstAidKit"};
		linkedItems[]={
			"adfrc_teamwendy_exfil_amcu_ct_Aus",
			"ADFRC_TBAS_T2_Rifleman_Pistol",
			"adfrc_facewear_Balaclava_amc_1",
			"adfrc_l3h_psq36",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_TBAS_T2_Rifleman_Pistol",
			"adfrc_facewear_Balaclava_amc_1",
			"adfrc_l3h_psq36",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class ADFRC_MD_AMCU_Soldier_HATGunner: ADFRC_MD_AMCU_Soldier_Rolled_Base{ // Rolled Sleeves
		displayName="Rifleman (HAT)";
		author="$STR_ADF_AUTHOR";
		scope=2;
		scopeCurator=2;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\AMCU_Soldier_HATGunner.jpg";
		class SpeechVariants{
			class Default{
				speechSingular[]={
					"veh_infantry_AT_s"
				};
				speechPlural[]={
					"veh_infantry_AT_p"
				};
			};
		};
		textSingular="$STR_A3_nameSound_veh_infantry_AT_s";
		textPlural="$STR_A3_nameSound_veh_infantry_AT_p";
		nameSound="veh_infantry_AT_s";
		icon="iconManAT";
		role="MissileSpecialist";
		cost=130000;
		camouflage=1.5;
		secondaryAmmoCoef=0.5;
		threat[]={0.80000001,0.80000001,0.30000001}; // From vanilla values
		backpack="ADFRC_CarryAll_AMCU_HAT";
		weapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_carlgustav_m3",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_carlgustav_m3",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		magazines[]={
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"16Rnd_9x21_Mag",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE",
			"SmokeShell",
			"SmokeShell"
		};
		respawnMagazines[]={
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"16Rnd_9x21_Mag",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE",
			"SmokeShell",
			"SmokeShell"
		};
		linkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class ADFRC_MD_AMCU_Soldier_MATGunner: ADFRC_MD_AMCU_Soldier_Rolled_Base{ // Rolled Sleeves
		displayName="Rifleman (MAT)";
		author="$STR_ADF_AUTHOR";
		scope=2;
		scopeCurator=2;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\AMCU_Soldier_MATGunner.jpg";
		class SpeechVariants{
			class Default{
				speechSingular[]={
					"veh_infantry_AT_s"
				};
				speechPlural[]={
					"veh_infantry_AT_p"
				};
			};
		};
		textSingular="$STR_A3_nameSound_veh_infantry_AT_s";
		textPlural="$STR_A3_nameSound_veh_infantry_AT_p";
		nameSound="veh_infantry_AT_s";
		icon="iconManAT";
		role="MissileSpecialist";
		cost=130000;
		secondaryAmmoCoef=0.5;
		threat[]={0.80000001,0.80000001,0.30000001}; // From vanilla values
		backpack="ADFRC_CarryAll_AMCU_MAT";
		weapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_carlgustav_m3",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_carlgustav_m3",
			"ADFRC_hpII",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]={
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"16Rnd_9x21_Mag",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE",
			"SmokeShell",
			"SmokeShell"
		};
		respawnMagazines[]={
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"16Rnd_9x21_Mag",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE",
			"SmokeShell",
			"SmokeShell"
		};
		linkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class ADFRC_MD_AMCU_Soldier_LATGunner: ADFRC_MD_AMCU_Soldier_Rolled_Base{ // Rolled Sleeves
		displayName="Rifleman (LAT)";
		author="$STR_ADF_AUTHOR";
		scope=2;
		scopeCurator=2;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\AMCU_Soldier_LATGunner.jpg";
		class SpeechVariants{
			class Default{
				speechSingular[]={
					"veh_infantry_AT_s"
				};
				speechPlural[]={
					"veh_infantry_AT_p"
				};
			};
		};
		textSingular="$STR_A3_nameSound_veh_infantry_AT_s";
		textPlural="$STR_A3_nameSound_veh_infantry_AT_p";
		nameSound="veh_infantry_AT_s";
		icon="iconManAT";
		role="MissileSpecialist";
		cost=130000;
		secondaryAmmoCoef=0.5;
		threat[]={0.80000001,0.80000001,0.30000001}; // From vanilla values
		//backpack="";
		weapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_carlgustav_m3",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_carlgustav_m3",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		magazines[]={
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"16Rnd_9x21_Mag",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE",
			"SmokeShell",
			"SmokeShell"
		};
		respawnMagazines[]={
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"16Rnd_9x21_Mag",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE",
			"SmokeShell",
			"SmokeShell"
		};
		linkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class ADFRC_MD_AMCU_Soldier_CFA: ADFRC_MD_AMCU_Soldier_Rolled_Base{ // Rolled Sleeves
		displayName="Combat First Aider";
		author="$STR_ADF_AUTHOR";
		scope=2;
		scopeCurator=2;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\AMCU_Soldier_CFA.jpg";
		class SpeechVariants{
			class Default{
				speechSingular[]={
					"veh_infantry_medic_s"
				};
				speechPlural[]={
					"veh_infantry_medic_p"
				};
			};
		};
		textSingular="$STR_A3_nameSound_veh_infantry_medic_s";
		textPlural="$STR_A3_nameSound_veh_infantry_medic_p";
		nameSound="veh_infantry_medic_s";
		icon="iconManMedic";
		role="CombatLifeSaver";
		picture="pictureHeal";
		attendant=1;
		camouflage=1.6;
		//threat[]={0.80000001,0.1,0.1}; <---For us to tweak the threat it poses to other units https://community.bistudio.com/wiki/CfgVehicles_Config_Reference#threat 
		backpack="ADFRC_CarryAll_AMCU_MED_CFA";
		weapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		magazines[]={
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		respawnMagazines[]={
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		linkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};	
	};
	class ADFRC_MD_AMCU_Soldier_Engineer: ADFRC_MD_AMCU_Soldier_Rolled_Base{ // Rolled Sleeves
		displayName="Combat Engineer";
		author="$STR_ADF_AUTHOR";
		scope=2;
		scopeCurator=2;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\AMCU_Soldier_Engineer.jpg";
		icon="iconManExplosive";
		role="Sapper";
		picture="pictureExplosive";
		cost=93000;
		camouflage=1.6;
		engineer=1;
		canDeactivateMines=1;
		detectSkill=38;
		//threat[]={0.80000001,0.1,0.1}; <---For us to tweak the threat it poses to other units https://community.bistudio.com/wiki/CfgVehicles_Config_Reference#threat 
		backpack="ADFRC_CarryAll_AMCU_Engineer";
		weapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		magazines[]={
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		respawnMagazines[]={
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		linkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class ADFRC_MD_AMCU_Soldier_Mine: ADFRC_MD_AMCU_Soldier_Rolled_Base{ // Rolled Sleeves
		displayName="Mine Specialist";
		author="$STR_ADF_AUTHOR";
		scope=2;
		scopeCurator=2;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\AMCU_Soldier_Mine.jpg";
		icon="iconManExplosive";
		role="Sapper";
		picture="pictureExplosive";
		cost=93000;
		camouflage=1.6;
		canDeactivateMines=1;
		detectSkill=38;
		//threat[]={0.80000001,0.1,0.1}; <---For us to tweak the threat it poses to other units https://community.bistudio.com/wiki/CfgVehicles_Config_Reference#threat 
		backpack="ADFRC_CarryAll_AMCU_Mine";
		weapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		magazines[]={
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		respawnMagazines[]={
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		linkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class ADFRC_MD_AMCU_Soldier_HeliPilot: ADFRC_MD_AMCU_Soldier_Base{
		displayName="Helicopter Pilot";
		author="$STR_ADF_AUTHOR";
		scope=2;
		scopeCurator=2;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\AMCU_Soldier_HeliPilot.jpg";
		class SpeechVariants{
			class Default{
				speechSingular[]={
					"veh_infantry_pilot_s"
				};
				speechPlural[]={
					"veh_infantry_pilot_p"
				};
			};
		};
		textSingular="$STR_A3_nameSound_veh_infantry_pilot_s";
		textPlural="$STR_A3_nameSound_veh_infantry_pilot_p";
		nameSound="veh_infantry_pilot_s";
		role="Crewman";
		camouflage=2;
		cost=93000;
		armor=2;
		armorStructural=2;
		explosionShielding=0.2;
		uniformClass="U_B_HeliPilotCoveralls";
		//threat[]={0.80000001,0.1,0.1}; <---For us to tweak the threat it poses to other units https://community.bistudio.com/wiki/CfgVehicles_Config_Reference#threat 
		//backpack="";
		weapons[]={
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		magazines[]={
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE",
			"SmokeShell",
			"SmokeShellRed",
			"SmokeShellPurple"
		};
		respawnMagazines[]={
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE",
			"SmokeShell",
			"SmokeShellRed",
			"SmokeShellPurple"
		};
		linkedItems[]={
			"H_PilotHelmetHeli_O",
			"V_TacVest_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"H_PilotHelmetHeli_O",
			"V_TacVest_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class ADFRC_MD_AMCU_Soldier_HeliCrew: ADFRC_MD_AMCU_Soldier_HeliPilot{
		displayName="Helicopter Crew";
		author="$STR_ADF_AUTHOR";
		scope=2;
		scopeCurator=2;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\AMCU_Soldier_HeliCrew.jpg";
		uniformClass="U_B_HeliPilotCoveralls";
		weapons[]={
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		magazines[]={
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE",
			"SmokeShell",
			"SmokeShellRed",
			"SmokeShellPurple"
		};
		respawnMagazines[]={
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE",
			"SmokeShell",
			"SmokeShellRed",
			"SmokeShellPurple"
		};
		linkedItems[]={
			"H_CrewHelmetHeli_O",
			"V_TacVest_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"H_CrewHelmetHeli_O",
			"V_TacVest_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class ADFRC_MD_AMCU_Soldier_Crewman: ADFRC_MD_AMCU_Soldier_Base{
		displayName="Crewman";
		author="$STR_ADF_AUTHOR";
		scope=2;
		scopeCurator=2;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\AMCU_Soldier_Crewman.jpg";
		role="Crewman";
		cost=93000;
		camouflage=1.6;
		//threat[]={0.80000001,0.1,0.1}; <---For us to tweak the threat it poses to other units https://community.bistudio.com/wiki/CfgVehicles_Config_Reference#threat 
		//backpack="";
		weapons[]={
			"arifle_AUG_C_black_F",
			"ADFRC_hpII",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]={
			"arifle_AUG_C_black_F",
			"ADFRC_hpII",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]={
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"16Rnd_9x21_Mag",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE",
			"SmokeShell",
			"SmokeShell"
		};
		respawnMagazines[]={
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"16Rnd_9x21_Mag",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE",
			"SmokeShell",
			"SmokeShell"
		};
		linkedItems[]={
			"H_HelmetCrew_I",
			"ADFRC_LPC_Tan_1",
			"adfrc_facewear_Shemagh_cbr_gatorz_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"H_HelmetCrew_I",
			"ADFRC_LPC_Tan_1",
			"adfrc_facewear_Shemagh_cbr_gatorz_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class ADFRC_MD_AMCU_Soldier_CavalryScout: ADFRC_MD_AMCU_Soldier_Base{
		displayName="Cavalry Scout";
		author="$STR_ADF_AUTHOR";
		scope=2;
		scopeCurator=2;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\AMCU_Soldier_CavalryScout.jpg";
		role="Rifleman";
		threat[]={0.70000001,0.1,0.1};
		//threat[]={0.80000001,0.1,0.1}; <---For us to tweak the threat it poses to other units https://community.bistudio.com/wiki/CfgVehicles_Config_Reference#threat 
		//backpack="";
		weapons[]={
			"arifle_AUG_C_black_F",
			"ADFRC_hpII",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]={
			"arifle_AUG_C_black_F",
			"ADFRC_hpII",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]={
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"16Rnd_9x21_Mag",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE",
			"SmokeShell",
			"SmokeShell"
		};
		respawnMagazines[]={
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"16Rnd_9x21_Mag",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE",
			"SmokeShell",
			"SmokeShell"
		};
		linkedItems[]={
			"H_Cap_headphones",
			"ADFRC_LPC_Tan_2",
			"adfrc_facewear_kondor_blk_blk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"H_Cap_headphones",
			"ADFRC_LPC_Tan_2",
			"adfrc_facewear_kondor_blk_blk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};	
	class ADFRC_MD_AMCU_Soldier_AmmoBearer: ADFRC_MD_AMCU_Soldier_Rolled_Base{ // Rolled Sleeves
		displayName="Ammobearer";
		author="$STR_ADF_AUTHOR";
		scope=2;
		scopeCurator=2;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\AMCU_Soldier_AmmoBearer.jpg";
		role="Rifleman";
		camouflage=1.5;
		//threat[]={0.80000001,0.1,0.1}; <---For us to tweak the threat it poses to other units https://community.bistudio.com/wiki/CfgVehicles_Config_Reference#threat 
		//backpack="ADFRC_CarryAll_AMCU_AB";
		weapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		magazines[]={
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE",
			"SmokeShell",
			"SmokeShell"
		};
		respawnMagazines[]={
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE",
			"SmokeShell",
			"SmokeShell"
		};
		linkedItems[]={
			"adfrc_ECH_amcu",
			"ADFRC_carrierLite_amcu",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"adfrc_ECH_amcu",
			"ADFRC_carrierLite_amcu",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class ADFRC_MD_AMCU_Soldier_GSMGAsst: ADFRC_MD_AMCU_Soldier_Rolled_Base{ // Rolled Sleeves
		displayName="General Support Gunner Assistant";
		author="$STR_ADF_AUTHOR";
		scope=2;
		scopeCurator=2;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\AMCU_Soldier_GSMGAsst.jpg";
		role="Rifleman";
		camouflage=1.5;
		//threat[]={0.80000001,0.1,0.1}; <---For us to tweak the threat it poses to other units https://community.bistudio.com/wiki/CfgVehicles_Config_Reference#threat 
		backpack="ADFRC_CarryAll_AMCU_GSMG";
		weapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		magazines[]={
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		respawnMagazines[]={
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		linkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class ADFRC_MD_AMCU_Soldier_HATAsst: ADFRC_MD_AMCU_Soldier_Rolled_Base{ // Rolled Sleeves
		displayName="Rifleman (HAT Asst.)";
		author="$STR_ADF_AUTHOR";
		scope=2;
		scopeCurator=2;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\AMCU_Soldier_HATAsst.jpg";
		role="Rifleman";
		camouflage=1.5;
		//threat[]={0.80000001,0.1,0.1}; <---For us to tweak the threat it poses to other units https://community.bistudio.com/wiki/CfgVehicles_Config_Reference#threat 
		//backpack="ADFRC_CarryAll_AMCU_HAT";
		weapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		magazines[]={
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE",
			"SmokeShell",
			"SmokeShell"
		};
		respawnMagazines[]={
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE",
			"SmokeShell",
			"SmokeShell"
		};
		linkedItems[]={
			"adfrc_ECH_amcu",
			"ADFRC_carrierLite_amcu",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"adfrc_ECH_amcu",
			"ADFRC_carrierLite_amcu",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class ADFRC_MD_AMCU_Soldier_MATAsst: ADFRC_MD_AMCU_Soldier_Rolled_Base{ // Rolled Sleeves
		displayName="Rifleman (MAT Asst.)";
		author="$STR_ADF_AUTHOR";
		scope=2;
		scopeCurator=2;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\AMCU_Soldier_MATAsst.jpg";
		role="Rifleman";
		camouflage=1.5;
		//threat[]={0.80000001,0.1,0.1}; <---For us to tweak the threat it poses to other units https://community.bistudio.com/wiki/CfgVehicles_Config_Reference#threat 
		//backpack="ADFRC_CarryAll_AMCU_MAT";
		weapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		magazines[]={
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE",
			"SmokeShell",
			"SmokeShell"
		};
		respawnMagazines[]={
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE",
			"SmokeShell",
			"SmokeShell"
		};
		linkedItems[]={
			"adfrc_ECH_amcu",
			"ADFRC_carrierLite_amcu",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"adfrc_ECH_amcu",
			"ADFRC_carrierLite_amcu",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class ADFRC_MD_AMCU_Soldier_MMGAsst: ADFRC_MD_AMCU_Soldier_Rolled_Base{ // Rolled Sleeves
		displayName="Rifleman (MMG Asst.)";
		author="$STR_ADF_AUTHOR";
		scope=2;
		scopeCurator=2;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\AMCU_Soldier_MMGAsst.jpg";
		role="Rifleman";
		camouflage=1.5;
		//threat[]={0.80000001,0.1,0.1}; <---For us to tweak the threat it poses to other units https://community.bistudio.com/wiki/CfgVehicles_Config_Reference#threat 
		//backpack="ADFRC_CarryAll_AMCU_MMG";
		weapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		magazines[]={
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE",
			"SmokeShell",
			"SmokeShell"
		};
		respawnMagazines[]={
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE",
			"SmokeShell",
			"SmokeShell"
		};
		linkedItems[]={
			"adfrc_ECH_amcu",
			"ADFRC_carrierLite_amcu",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"adfrc_ECH_amcu",
			"ADFRC_carrierLite_amcu",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class ADFRC_MD_AMCU_Soldier_Shotgun: ADFRC_MD_AMCU_Soldier_Base{
		displayName="Rifleman (870)";
		author="$STR_ADF_AUTHOR";
		scope=1;
		scopeCurator=1;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\AMCU_Soldier_Shotgun.jpg";
		role="Rifleman";
		camouflage=1.5;
		//threat[]={0.80000001,0.1,0.1}; <---For us to tweak the threat it poses to other units https://community.bistudio.com/wiki/CfgVehicles_Config_Reference#threat 
		//backpack="";
		weapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		magazines[]={
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		respawnMagazines[]={
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		linkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class ADFRC_MD_AMCU_Soldier_Unarmed: ADFRC_MD_AMCU_Soldier_Tee_Base{
		displayName="Rifleman (Unarmed)";
		author="$STR_ADF_AUTHOR";
		scope=2;
		scopeCurator=2;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\AMCU_Soldier_Unarmed.jpg";
		role="Unarmed";
		threat[]={0.1,0.1,0.1}; // From vanilla values
		weapons[]={
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"Throw",
			"Put"
		};
		magazines[]={};
		respawnMagazines[]={};
		linkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	////////////////////////Support Units///////////////////////////////////////////////////////////
	class ADFRC_MD_AMCU_Support_AMor: ADFRC_MD_AMCU_Soldier_Base{
		displayName="Asst. Gunner (Mortar)";
		author="$STR_ADF_AUTHOR";
		scope=2;
		scopeCurator=2;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\AMCU_Support_AMor.jpg";
		vehicleClass="MenSupport";
		role="Assistant";
		cost=220000;
		camouflage=1.5;
		//threat[]={0.80000001,0.1,0.1}; <---For us to tweak the threat it poses to other units https://community.bistudio.com/wiki/CfgVehicles_Config_Reference#threat
		backpack="B_Mortar_01_support_F";
		weapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		magazines[]={
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		respawnMagazines[]={
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		linkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class ADFRC_MD_AMCU_Support_AMG: ADFRC_MD_AMCU_Soldier_Base{
		displayName="Asst. Gunner (HMG/GMG)";
		author="$STR_ADF_AUTHOR";
		scope=2;
		scopeCurator=2;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\AMCU_Support_AMG.jpg";
		vehicleClass="MenSupport";
		role="Assistant";
		cost=220000;
		camouflage=1.5;
		//threat[]={0.80000001,0.1,0.1}; <---For us to tweak the threat it poses to other units https://community.bistudio.com/wiki/CfgVehicles_Config_Reference#threat
		backpack="B_HMG_01_support_F";
		weapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		magazines[]={
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		respawnMagazines[]={
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		linkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class ADFRC_MD_AMCU_Support_GMG: ADFRC_MD_AMCU_Soldier_Base{
		displayName="Gunner (GMG)";
		author="$STR_ADF_AUTHOR";
		scope=2;
		scopeCurator=2;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\AMCU_Support_GMG.jpg";
		vehicleClass="MenSupport";
		role="Assistant";
		cost=220000;
		camouflage=1.5;
		//threat[]={0.80000001,0.1,0.1}; <---For us to tweak the threat it poses to other units https://community.bistudio.com/wiki/CfgVehicles_Config_Reference#threat
		backpack="B_GMG_01_weapon_F";
		weapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		magazines[]={
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		respawnMagazines[]={
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		linkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class ADFRC_MD_AMCU_Support_HMG: ADFRC_MD_AMCU_Soldier_Base{
		displayName="Gunner (HMG)";
		author="$STR_ADF_AUTHOR";
		scope=2;
		scopeCurator=2;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\AMCU_Support_HMG.jpg";
		vehicleClass="MenSupport";
		role="Assistant";
		cost=220000;
		camouflage=1.5;
		//threat[]={0.80000001,0.1,0.1}; <---For us to tweak the threat it poses to other units https://community.bistudio.com/wiki/CfgVehicles_Config_Reference#threat
		backpack="B_HMG_01_weapon_F";
		weapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		magazines[]={
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		respawnMagazines[]={
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		linkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class ADFRC_MD_AMCU_Support_Mort: ADFRC_MD_AMCU_Soldier_Base{
		displayName="Gunner (Mortar)";
		author="$STR_ADF_AUTHOR";
		scope=2;
		scopeCurator=2;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\AMCU_Support_Mort.jpg";
		vehicleClass="MenSupport";
		role="Assistant";
		cost=220000;
		camouflage=1.5;
		//threat[]={0.80000001,0.1,0.1}; <---For us to tweak the threat it poses to other units https://community.bistudio.com/wiki/CfgVehicles_Config_Reference#threat
		backpack="B_Mortar_01_weapon_F";
		weapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		magazines[]={
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		respawnMagazines[]={
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		linkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class ADFRC_MD_AMCU_Support_UAV: ADFRC_MD_AMCU_Soldier_Base{
		displayName="UAV Operator";
		author="$STR_ADF_AUTHOR";
		scope=2;
		scopeCurator=2;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\AMCU_Support_UAV.jpg";
		vehicleClass="MenSupport";
		role="SpecialOperative";
		uavHacker=1;
		//threat[]={0.80000001,0.1,0.1}; <---For us to tweak the threat it poses to other units https://community.bistudio.com/wiki/CfgVehicles_Config_Reference#threat
		backpack="B_UAV_01_backpack_F";
		weapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		magazines[]={
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		respawnMagazines[]={
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		linkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"B_UavTerminal"
		};
		respawnLinkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"B_UavTerminal"
		};
	};