	////////////////////////Recon Units/////////////////////////////////////////////////////////////
	class ADFRC_MD_AMCU_Recon_Base;
	class ADFRC_MD_AMCU_Recon_Rolled_Base;
	class ADFRC_MD_AMCU_Sniper_Temperate_Base;
	class ADFRC_MD_AMCU_Sniper_Tropical_Base;
	class ADFRC_MD_AMCU_Sniper_Arid_Base;
	class ADFRC_MD_AMCU_Recon_F: ADFRC_MD_AMCU_Recon_Base{
		displayName="Recon Scout";
		author="$STR_ADF_AUTHOR";
		scope=2;
		scopeCurator=2;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\AMCU_Recon_F.jpg";
		role="Rifleman";
		//threat[]={0.80000001,0.1,0.1}; <---For us to tweak the threat it poses to other units https://community.bistudio.com/wiki/CfgVehicles_Config_Reference#threat
		backpack = "ADFRC_BP_Hydration_AMCU_1";
		weapons[]={
			"arifle_AUG_black_Spectr_flash_Sup_F",
			"ADFRC_WP_F9_SWS",
			"Rangefinder",
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"arifle_AUG_black_Spectr_flash_Sup_F",
			"ADFRC_WP_F9_SWS",
			"Rangefinder",
			"Throw",
			"Put"
		};
		magazines[]={
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_mixed_ef88",
			"ADFRC_30Rnd_aug_mixed_ef88",
			"ADFRC_17rnd_9MM_BALL_F9",
			"ADFRC_17rnd_9MM_BALL_F9",
			"ADFRC_17rnd_9MM_BALL_F9",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		respawnMagazines[]={
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_mixed_ef88",
			"ADFRC_30Rnd_aug_mixed_ef88",
			"ADFRC_17rnd_9MM_BALL_F9",
			"ADFRC_17rnd_9MM_BALL_F9",
			"ADFRC_17rnd_9MM_BALL_F9",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		items[] = {"FirstAidKit", "FirstAidKit", "FirstAidKit", "FirstAidKit", "FirstAidKit"};
		linkedItems[]={
			"adfrc_boonie",
			"ADFRC_TBAS_T0_AMCU_Rifleman",
			"adfrc_facewear_Balaclava_amc_1",
			"adfrc_l3h_psq36_recce",
			"ItemMap",
			"ItemGPS",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"adfrc_boonie",
			"ADFRC_TBAS_T0_AMCU_Rifleman",
			"adfrc_facewear_Balaclava_amc_1",
			"adfrc_l3h_psq36_recce",
			"ItemMap",
			"ItemGPS",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class ADFRC_MD_AMCU_Recon_TL: ADFRC_MD_AMCU_Recon_Base{
		displayName="Recon Team Leader";
		author="$STR_ADF_AUTHOR";
		scope=2;
		scopeCurator=2;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\AMCU_Recon_TL.jpg";
		icon="iconManLeader";
		role="Rifleman";
		cost=250000;
		backpack = "adfrc_molle_bag_ASIP";
		weapons[]={
			"arifle_AUG_black_Spectr_flash_Sup_F",
			"ADFRC_WP_F9_SWS",
			"Laserdesignator",
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"arifle_AUG_black_Spectr_flash_Sup_F",
			"ADFRC_WP_F9_SWS",
			"Laserdesignator",
			"Throw",
			"Put"
		};
		magazines[]={
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_mixed_ef88",
			"ADFRC_30Rnd_aug_mixed_ef88",
			"ADFRC_17rnd_9MM_BALL_F9",
			"ADFRC_17rnd_9MM_BALL_F9",
			"ADFRC_17rnd_9MM_BALL_F9",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_blue", 
			"Chemlight_blue",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE",
			"Laserbatteries"
		};
		respawnMagazines[]={
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_mixed_ef88",
			"ADFRC_30Rnd_aug_mixed_ef88",
			"ADFRC_17rnd_9MM_BALL_F9",
			"ADFRC_17rnd_9MM_BALL_F9",
			"ADFRC_17rnd_9MM_BALL_F9",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_blue", 
			"Chemlight_blue",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE",
			"Laserbatteries"
		};
		items[] = {"FirstAidKit", "FirstAidKit", "FirstAidKit", "FirstAidKit", "FirstAidKit"};
		linkedItems[]={
			"adfrc_boonie",
			"ADFRC_TBAS_T0_AMCU_TL",
			"adfrc_facewear_Balaclava_olv_1",
			"adfrc_l3h_psq36_recce",
			"ItemMap",
			"ItemGPS",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"adfrc_boonie",
			"ADFRC_TBAS_T0_AMCU_TL",
			"adfrc_facewear_Balaclava_olv_1",
			"adfrc_l3h_psq36_recce",
			"ItemMap",
			"ItemGPS",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class ADFRC_MD_AMCU_Recon_CFA: ADFRC_MD_AMCU_Recon_Base{
		displayName="Recon Combat First Aider";
		author="$STR_ADF_AUTHOR";
		scope=2;
		scopeCurator=2;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\AMCU_Recon_CFA.jpg";
		icon="iconManMedic";
		role="CombatLifeSaver";
		picture="pictureHeal";
		attendant=1;
		camouflage=1.6;
		//threat[]={0.80000001,0.1,0.1}; <---For us to tweak the threat it poses to other units https://community.bistudio.com/wiki/CfgVehicles_Config_Reference#threat 
		backpack = "ADFRC_BP_TacBag_AMCU_1";
		weapons[]={
			"arifle_AUG_black_Spectr_flash_Sup_F",
			"ADFRC_WP_F9_SWS",
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"arifle_AUG_black_Spectr_flash_Sup_F",
			"ADFRC_WP_F9_SWS",
			"Throw",
			"Put"
		};
		magazines[]={
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_17rnd_9MM_BALL_F9",
			"ADFRC_17rnd_9MM_BALL_F9",
			"ADFRC_17rnd_9MM_BALL_F9",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_blue",
			"Chemlight_blue",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		respawnMagazines[]={
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_mixed_ef88",
			"ADFRC_30Rnd_aug_mixed_ef88",
			"ADFRC_17rnd_9MM_BALL_F9",
			"ADFRC_17rnd_9MM_BALL_F9",
			"ADFRC_17rnd_9MM_BALL_F9",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		items[] = {"FirstAidKit", "FirstAidKit", "FirstAidKit", "FirstAidKit", "FirstAidKit", "Medikit"};
		linkedItems[]={
			"adfrc_boonie",
			"ADFRC_TBAS_T0_AMCU_CFA",
			"adfrc_facewear_Balaclava_amc_1",
			"adfrc_l3h_psq36_recce",
			"ItemMap",
			"ItemGPS",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"adfrc_boonie",
			"ADFRC_TBAS_T0_AMCU_CFA",
			"adfrc_facewear_Balaclava_amc_1",
			"adfrc_l3h_psq36_recce",
			"ItemMap",
			"ItemGPS",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class ADFRC_MD_AMCU_Recon_LSW: ADFRC_MD_AMCU_Recon_Base{
		displayName="Recon LSW Gunner";
		author="$STR_ADF_AUTHOR";
		scope=2;
		scopeCurator=2;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\AMCU_Recon_LSW.jpg";
		icon="iconManMG";
		role="MachineGunner";
		cost=220000;
		//threat[]={0.80000001,0.1,0.1}; <---For us to tweak the threat it poses to other units https://community.bistudio.com/wiki/CfgVehicles_Config_Reference#threat 
		backpack = "ADFRC_BP_Assault_AMCU_1";
		weapons[]={
			"ADFRC_minimi_elcan",
			"ADFRC_WP_F9_SWS",
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"ADFRC_minimi_elcan",
			"ADFRC_WP_F9_SWS",
			"Throw",
			"Put"
		};
		magazines[]={
			"ADFRC_100Rnd_556_Belt",
			"ADFRC_100Rnd_556_Belt",
			"ADFRC_100Rnd_556_Belt",
			"ADFRC_100Rnd_556_Belt",
			"ADFRC_100Rnd_556_Belt",
			"ADFRC_100Rnd_556_Belt",
			"ADFRC_17rnd_9MM_BALL_F9",
			"ADFRC_17rnd_9MM_BALL_F9",
			"ADFRC_17rnd_9MM_BALL_F9",
			"SmokeShell",
			"ADFRC_F1_GRENADE"
		};
		respawnMagazines[]={
			"ADFRC_100Rnd_556_Belt",
			"ADFRC_100Rnd_556_Belt",
			"ADFRC_100Rnd_556_Belt",
			"ADFRC_100Rnd_556_Belt",
			"ADFRC_100Rnd_556_Belt",
			"ADFRC_100Rnd_556_Belt",
			"ADFRC_17rnd_9MM_BALL_F9",
			"ADFRC_17rnd_9MM_BALL_F9",
			"ADFRC_17rnd_9MM_BALL_F9",
			"SmokeShell",
			"ADFRC_F1_GRENADE"
		};
		items[] = {"FirstAidKit", "FirstAidKit", "FirstAidKit", "FirstAidKit", "FirstAidKit"};
		linkedItems[]={
			"adfrc_boonie",
			"ADFRC_TBAS_T0_AMCU_LMG",
			"adfrc_facewear_Balaclava_amc_1",
			"adfrc_l3h_psq36_recce_recce",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"adfrc_boonie",
			"ADFRC_TBAS_T0_AMCU_LMG",
			"adfrc_facewear_Balaclava_amc_1",
			"adfrc_l3h_psq36_recce_recce",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	
	
////// SNIPERS TO BE COMPLETED WHEN BRUCEY HAS ADDED WEAPONS
	class ADFRC_MD_AMCU_Recon_Sniper_MRSASS: ADFRC_MD_AMCU_Sniper_Temperate_Base{
		displayName="Sniper (SR-25)";
		author="$STR_ADF_AUTHOR";
		scope=1;
		scopeCurator=1;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\AMCU_Recon_Sniper_MRSASS.jpg";
		role="Marksman";
		cost=250000;
		threat[]={0.80000001,0.30000001,0.30000001};
		//backpack="ADFRC_Kitbag_AMCU";
		weapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_WP_F9_SWS",
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_WP_F9_SWS",
			"Throw",
			"Put"
		};
		magazines[]={
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		respawnMagazines[]={
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		linkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_TBAS_T0_AMCU_S_SR25",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_TBAS_T0_AMCU_S_SR25",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class ADFRC_MD_AMCU_Recon_Sniper: ADFRC_MD_AMCU_Sniper_Temperate_Base{
		displayName="Sniper (SR-98)";
		author="$STR_ADF_AUTHOR";
		scope=1;
		scopeCurator=1;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\AMCU_Recon_Sniper.jpg";
		role="Marksman";
		cost=250000;
		threat[]={0.80000001,0.30000001,0.30000001};
		//backpack="ADFRC_Kitbag_AMCU";
		weapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_WP_F9_SWS",
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_WP_F9_SWS",
			"Throw",
			"Put"
		};
		magazines[]={
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		respawnMagazines[]={
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		linkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_TBAS_T0_AMCU_S_SR98",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_TBAS_T0_AMCU_S_SR98",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class ADFRC_MD_AMCU_Recon_Sniper_LRAP: ADFRC_MD_AMCU_Sniper_Temperate_Base{
		displayName="Sniper (Blaser)";
		author="$STR_ADF_AUTHOR";
		scope=1;
		scopeCurator=1;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\AMCU_Recon_Sniper_LRAP.jpg";
		role="Marksman";
		cost=250000;
		threat[]={0.80000001,0.30000001,0.30000001};
		//backpack="ADFRC_Kitbag_AMCU";
		weapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_WP_F9_SWS",
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_WP_F9_SWS",
			"Throw",
			"Put"
		};
		magazines[]={
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		respawnMagazines[]={
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		linkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_TBAS_T0_AMCU_S_Tac2",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_TBAS_T0_AMCU_S_Tac2",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class ADFRC_MD_AMCU_Recon_Sniper_AM: ADFRC_MD_AMCU_Sniper_Temperate_Base{
		displayName="Sniper (AW50F)";
		author="$STR_ADF_AUTHOR";
		scope=1;
		scopeCurator=1;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\AMCU_Recon_Sniper_AM.jpg";
		role="Marksman";
		cost=250000;
		threat[]={0.80000001,0.30000001,0.30000001};
		//backpack="ADFRC_Kitbag_AMCU";
		weapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_WP_F9_SWS",
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_WP_F9_SWS",
			"Throw",
			"Put"
		};
		magazines[]={
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		respawnMagazines[]={
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"ADFRC_30Rnd_aug_ef88",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		items[] = {"FirstAidKit", "FirstAidKit", "FirstAidKit", "FirstAidKit", "FirstAidKit"};
		linkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_TBAS_T0_AMCU_S_AW50F",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_TBAS_T0_AMCU_S_AW50F",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};