# .github/ISSUE_TEMPLATE/feature_request.yml

name: Feature/Asset Request
description: Request a new feature or asset for ADF Re-Cut
title: "[REQUEST] Short and sweet name for your request "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Got an idea for a new feature or asset? Let us know what you'd like to see added to ADF Re-Cut.
  
  - type: dropdown
    id: request_type
    attributes:
      label: Request Type
      description: What kind of request is this?
      options:
        - New Asset (Vehicle, Weapon, Equipment)
        - New Feature (Gameplay, Scripting)
        - Config Improvement
        - Quality of Life
        - Other
    validations:
      required: true
  
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What would you like to see added or changed?
      placeholder: |
        Describe the asset or feature in detail. For assets, include what it is and why it's relevant to ADF.
        For features, explain what functionality you're looking for.
    validations:
      required: true
  
  - type: textarea
    id: justification
    attributes:
      label: Why This Would Be Valuable
      description: How would this improve the mod or enhance gameplay?
      placeholder: |
        Explain why this addition makes sense for ADF Re-Cut.
        Does it fill a gap? Improve authenticity? Add gameplay value?
    validations:
      required: true
  
  - type: textarea
    id: references
    attributes:
      label: Reference Material
      description: Links, images, or examples that show what you're requesting
      placeholder: |
        - Links to reference photos
        - Examples from other mods
        - Real-world information
        - Videos or documentation
      render: markdown
  
  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: Any thoughts on how this could be implemented? (Optional)
      placeholder: |
        If you have ideas on how this could work technically or design-wise, share them here.
  
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Anything else we should know?
      placeholder: "Any other relevant information"