	////////////////////////SASR Units//////////////////////////////////////////////////////////////
	class ADFRC_MD_MC_SASR_Base;
	class ADFRC_MD_MC_SASR_Rolled_Base;
	class ADFRC_MD_MC_SASR_Tee_Base;
	class ADFRC_MD_SASR_Sniper_Temperate_Base;
	class ADFRC_MD_SASR_Sniper_Tropical_Base;
	class ADFRC_MD_SASR_Sniper_Arid_Base;
	class ADFRC_MD_MC_SASR_F: ADFRC_MD_MC_SASR_Base{
		displayName="Commando";
		author="$STR_ADF_AUTHOR";
		scope=2;
		scopeCurator=2;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\MC_SASR_F.jpg";
		role="Rifleman";
		//threat[]={0.80000001,0.1,0.1}; <---For us to tweak the threat it poses to other units https://community.bistudio.com/wiki/CfgVehicles_Config_Reference#threat
		//backpack="ADFRC_Kitbag_AMCU";
		weapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		magazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		respawnMagazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		linkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class ADFRC_MD_MC_SASR_CQB: ADFRC_MD_MC_SASR_Base{
		displayName="Commando (CQB)";
		author="$STR_ADF_AUTHOR";
		scope=2;
		scopeCurator=2;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\MC_SASR_CQB.jpg";
		role="Rifleman";
		//threat[]={0.80000001,0.1,0.1}; <---For us to tweak the threat it poses to other units https://community.bistudio.com/wiki/CfgVehicles_Config_Reference#threat
		//backpack="ADFRC_Kitbag_AMCU";
		weapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		magazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		respawnMagazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		linkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class ADFRC_MD_MC_SASR_Grenadier: ADFRC_MD_MC_SASR_Base{
		displayName="Grenadier";
		author="$STR_ADF_AUTHOR";
		scope=1;
		scopeCurator=1;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\MC_SASR_Grenadier.jpg";
		role="Rifleman";
		//threat[]={0.80000001,0.1,0.1}; <---For us to tweak the threat it poses to other units https://community.bistudio.com/wiki/CfgVehicles_Config_Reference#threat
		//backpack="ADFRC_Kitbag_AMCU";
		weapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		magazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		respawnMagazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		linkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class ADFRC_MD_MC_SASR_MMG: ADFRC_MD_MC_SASR_Rolled_Base{
		displayName="Gunner (Maximi)";
		author="$STR_ADF_AUTHOR";
		scope=2;
		scopeCurator=2;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\MC_SASR_MMG.jpg";
		icon="iconManMG";
		role="MachineGunner";
		cost=220000;
		//threat[]={0.80000001,0.1,0.1}; <---For us to tweak the threat it poses to other units https://community.bistudio.com/wiki/CfgVehicles_Config_Reference#threat 
		//backpack="ADFRC_Kitbag_AMCU";
		weapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		magazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		respawnMagazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		linkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class ADFRC_MD_MC_SASR_PatrolCom: ADFRC_MD_MC_SASR_Base{
		displayName="Patrol Commander";
		author="$STR_ADF_AUTHOR";
		scope=2;
		scopeCurator=2;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\MC_SASR_PatrolCom.jpg";
		icon="iconManLeader";
		role="Rifleman";
		cost=250000;
		//threat[]={0.80000001,0.1,0.1}; <---For us to tweak the threat it poses to other units https://community.bistudio.com/wiki/CfgVehicles_Config_Reference#threat
		//backpack="ADFRC_Kitbag_AMCU";
		weapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		magazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		respawnMagazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		linkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class ADFRC_MD_MC_SASR_TL: ADFRC_MD_MC_SASR_Rolled_Base{
		displayName="Team Leader";
		author="$STR_ADF_AUTHOR";
		scope=2;
		scopeCurator=2;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\MC_SASR_TL.jpg";
		icon="iconManLeader";
		role="Rifleman";
		cost=250000;
		//threat[]={0.80000001,0.1,0.1}; <---For us to tweak the threat it poses to other units https://community.bistudio.com/wiki/CfgVehicles_Config_Reference#threat
		//backpack="ADFRC_Kitbag_AMCU";
		weapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		magazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		respawnMagazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		linkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class ADFRC_MD_MC_SASR_CFA: ADFRC_MD_MC_SASR_Base{
		displayName="Combat First Aider";
		author="$STR_ADF_AUTHOR";
		scope=2;
		scopeCurator=2;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\MC_SASR_CFA.jpg";
		icon="iconManMedic";
		role="CombatLifeSaver";
		picture="pictureHeal";
		attendant=1;
		camouflage=1.6;
		//threat[]={0.80000001,0.1,0.1}; <---For us to tweak the threat it poses to other units https://community.bistudio.com/wiki/CfgVehicles_Config_Reference#threat 
		//backpack="ADFRC_Kitbag_AMCU";
		weapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		magazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		respawnMagazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		linkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class ADFRC_MD_MC_SASR_EOD: ADFRC_MD_MC_SASR_Base{
		displayName="Operator (EOD)";
		author="$STR_ADF_AUTHOR";
		scope=2;
		scopeCurator=2;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\MC_SASR_EOD.jpg";
		icon="iconManExplosive";
		role="Sapper";
		picture="pictureExplosive";
		cost=93000;
		camouflage=1.6;
		engineer=1;
		canDeactivateMines=1;
		detectSkill=38;
		//threat[]={0.80000001,0.1,0.1}; <---For us to tweak the threat it poses to other units https://community.bistudio.com/wiki/CfgVehicles_Config_Reference#threat
		//backpack="ADFRC_Kitbag_AMCU";
		weapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		magazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		respawnMagazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		linkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class ADFRC_MD_MC_SASR_Breacher: ADFRC_MD_MC_SASR_Base{
		displayName="Breacher (870)";
		author="$STR_ADF_AUTHOR";
		scope=2;
		scopeCurator=2;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\MC_SASR_Breacher.jpg";
		role="Rifleman";
		//threat[]={0.80000001,0.1,0.1}; <---For us to tweak the threat it poses to other units https://community.bistudio.com/wiki/CfgVehicles_Config_Reference#threat
		//backpack="ADFRC_Kitbag_AMCU";
		weapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		magazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		respawnMagazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		linkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class ADFRC_MD_MC_SASR_Sniper_LRAP: ADFRC_MD_SASR_Sniper_Temperate_Base{
		displayName="Sniper (Blaser)";
		author="$STR_ADF_AUTHOR";
		scope=1;
		scopeCurator=1;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\MC_SASR_Sniper_LRAP.jpg";
		role="Marksman";
		cost=250000;
		threat[]={0.80000001,0.30000001,0.30000001};
		//backpack="ADFRC_Kitbag_AMCU";
		weapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		magazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		respawnMagazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		linkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class ADFRC_MD_MC_SASR_Sniper_AM: ADFRC_MD_SASR_Sniper_Temperate_Base{
		displayName="Sniper (M107)";
		author="$STR_ADF_AUTHOR";
		scope=2;
		scopeCurator=2;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\MC_SASR_Sniper_AM.jpg";
		role="Marksman";
		cost=250000;
		threat[]={0.80000001,0.30000001,0.30000001};
		//backpack="ADFRC_Kitbag_AMCU";
		weapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		magazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		respawnMagazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		linkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class ADFRC_MD_MC_SASR_Sniper_MRSASS: ADFRC_MD_SASR_Sniper_Temperate_Base{
		displayName="Sniper (SR-25E2)";
		author="$STR_ADF_AUTHOR";
		scope=1;
		scopeCurator=1;
		editorPreview = "\ADF_Units\data\editorPreviews\MD\MC_SASR_Sniper_MRSASS.jpg";
		role="Marksman";
		cost=250000;
		threat[]={0.80000001,0.30000001,0.30000001};
		//backpack="ADFRC_Kitbag_AMCU";
		weapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		respawnWeapons[]={
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put"
		};
		magazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		respawnMagazines[]={
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		linkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]={
			"adfrc_opscore_marine_Snakeskin_amcu_Ct_1_Aus",
			"ADFRC_PC_Tan_1",
			"adfrc_facewear_ESS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};