class CfgPatches
{
	class ADFRC_uniform_amcu
	{
		units[]=
		{
			"ADFRC_AMCU_Soldier_Base",
			"ADFRC_rifleman_amcu",
			"ADFRC_rifleman_amcu_recon"
		};
		weapons[]=
		{
			"ADFRC_helmetC_amcu",
			"ADFRC_uniform_amcu",
			"ADFRC_uniform_amcu_recon"
		};
		requiredVersion=0.1;
		requiredAddons[]=
		{
			"A3_Weapons_F",
			"A3_Characters_F_BLUFOR",
			"ADF_Core"
		};
	};
};
class CfgEditorSubcategories
{
	class ADFRC_MEN_AMCU // Category class, you point to it in editorSubcategory property
	{
		displayName = "Men (Army AMCU)"; // Name visible in the list
	};
};
class cfgVehicles
{
	class ADFRC_Soldier_base_F;
	class ADFRC_AMCU_Soldier_Base: ADFRC_Soldier_base_F
	{
		scope=1;
		author="$STR_ADFRC_AUTHOR";
		faction="ADF";
		editorSubcategory= "ADFRC_MEN_AMCU";
		genericNames="NATOMen";
		nakedUniform="U_BasicBody";
		uniformClass="U_B_CombatUniform_mcam_vest";
		weapons[]=
		{
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put",
			"Binocular"
		};
		Items[]=
		{
			"FirstAidKit"
		};
		RespawnItems[]=
		{
			"FirstAidKit"
		};
		magazines[]=
		{
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		respawnMagazines[]=
		{
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		linkedItems[]=
		{
			"ADFRC_teamwendy_exfil_amcu_ct_2_Aus",
			"ADFRC_PC_Tan_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ADFRC_teamwendy_exfil_amcu_ct_2_Aus",
			"ADFRC_PC_Tan_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		backpack="ADFRC_AssaultPack_AMC_1_Backpanel";
	};
	class ADFRC_rifleman_amcu: ADFRC_amcu_Soldier_Base
	{
		scope=2;
		scopeCurator=2;
		author="$STR_ADF_AUTHOR";
		_generalMacro="ADFRC_rifleman_amcu";
		displayName="Rifleman";
		////editorPreview = "ADF_Units\ADFRC_men_amcu\preview\ADFRC_rifleman_amcu.jpg";
		editorSubcategory= "ADFRC_MEN_amcu";
		vehicleClass=$STR_ADF_MEN_amcu;
		uniformAccessories[]={};
		uniformClass="ADFRC_uniform_amcu";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"ADF_Units\ADFRC_men_amcu\data\clothing_recut_amc_u_co.paa"
		};
		backpack="adfrc_CarryAll_amc";
	};
	class ADFRC_engineer_amcu: ADFRC_rifleman_amcu
	{
		scope=2;
		scopeCurator=2;
		author="$STR_ADF_AUTHOR";
		_generalMacro="ADFRC_engineer_amcu";
		displayName="Combat Engineer";
		////editorPreview = "ADF_Units\ADFRC_men_amcu\preview\ADFRC_engineer_amcu.jpg";
		engineer=1;
		saboteur=1;
		canDeactivateMines=1;
		detectSkill=80;
		model="\A3\characters_F\BLUFOR\b_soldier_03.p3d";
		Items[]=
		{
			"FirstAidKit"
		};
		RespawnItems[]=
		{
			"FirstAidKit"
		};
		magazines[]=
		{
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		respawnMagazines[]=
		{
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		linkedItems[]=
		{
			"ADFRC_teamwendy_exfil_amcu_ct_2_Aus",
			"ADFRC_PC_Tan_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ADFRC_teamwendy_exfil_amcu_ct_2_Aus",
			"ADFRC_PC_Tan_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		backpack="adfrc_CarryAll_amcu_engineer";
		icon="iconManEngineer";
		picture="pictureRepair";
	};
	class ADFRC_grenadier_amcu: ADFRC_rifleman_amcu
	{
		scope=2;
		scopeCurator=2;
		author="$STR_ADF_AUTHOR";
		_generalMacro="ADFRC_grenadier_amcu";
		displayName="Grenadier";
		//editorPreview = "ADF_Units\ADFRC_men_amcu\preview\ADFRC_grenadier_amcu.jpg";
		weapons[]=
		{
			"arifle_AUG_GL_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"arifle_AUG_GL_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		respawnMagazines[]=
		{
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		backpack="ADFRC_Carryall_gl_amcu";
	};
	/*class ADFRC_marksman_amcu: ADFRC_rifleman_amcu
	{
		scope=2;
		author="$STR_ADF_AUTHOR";
		_generalMacro="ADFRC_marksman_amcu";
		displayName="Designated Marksman";
		//editorPreview = "ADF_Units\ADFRC_men_amcu\preview\ADFRC_marksman_amcu.jpg";
		uniformClass="ADFRC_uniform_amcu_tee";
		model="\A3\characters_F\BLUFOR\b_soldier_02.p3d";
		hiddenSelections[]=
		{
			"Camo",
			"Camo2"
		};
		hiddenSelectionsTextures[]=
		{
			"ADF_Units\ADFRC_men_amcu\data\uniform_amcu_co.paa",
			"ADF_Units\ADFRC_men_amcu\data\basicbody_army_co.paa"
		};
		weapons[]=
		{
			"ADFRC_hk417_sand_army",
			"ADFRC_hpII",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"ADFRC_hk417_sand_army",
			"ADFRC_hpII",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"16Rnd_9x21_Mag",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE",
			"SmokeShell",
			"SmokeShell"
		};
		respawnMagazines[]=
		{
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"16Rnd_9x21_Mag",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE",
			"SmokeShell",
			"SmokeShell"
		};
		backpack="";
	};*/
	class ADFRC_medic_amcu: ADFRC_rifleman_amcu
	{
		scope=2;
		author="$STR_ADF_AUTHOR";
		_generalMacro="ADFRC_amcu_Medic";
		displayName="Medical Technician";
		//editorPreview = "ADF_Units\ADFRC_men_amcu\preview\ADFRC_medic_amcu.jpg";
		attendant=1;
		model="\A3\characters_F\BLUFOR\b_soldier_03.p3d";
		uniformClass="ADFRC_uniform_amcu_medic";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"ADF_Units\ADFRC_men_amcu\data\clothing_recut_amc_u_co.paa"
		};
		Items[]=
		{
			"FirstAidKit"
		};
		RespawnItems[]=
		{
			"FirstAidKit"
		};
		magazines[]=
		{
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		respawnMagazines[]=
		{
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		linkedItems[]=
		{
			"ADFRC_teamwendy_exfil_amcu_ct_2_Aus",
			"ADFRC_PC_Tan_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ADFRC_teamwendy_exfil_amcu_ct_2_Aus",
			"ADFRC_PC_Tan_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		icon="iconManMedic";
		backpack="adfrc_CarryAll_amcu_Medic";
	};
	class ADFRC_riflemanAT_amcu: ADFRC_rifleman_amcu
	{
		scope=2;
		author="$STR_ADF_AUTHOR";
		_generalMacro="ADFRC_amcu_RiflemanAT";
		displayName="AT Gunner";
		//editorPreview = "ADF_Units\ADFRC_men_amcu\preview\ADFRC_riflemanAT_amcu.jpg";
		model="\A3\characters_F\BLUFOR\b_soldier_03.p3d";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"ADF_Units\ADFRC_men_amcu\data\uniform_amcu_co.paa"
		};
		weapons[]=
		{
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_carlgustav_m3",
			"ADFRC_hpII",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_carlgustav_m3",
			"ADFRC_hpII",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE",
			"SmokeShell",
			"SmokeShell"
		};
		respawnMagazines[]=
		{
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE",
			"SmokeShell",
			"SmokeShell"
		};
		linkedItems[]=
		{
			"ADFRC_teamwendy_exfil_amcu_ct_2_Aus",
			"ADFRC_PC_Tan_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ADFRC_teamwendy_exfil_amcu_ct_2_Aus",
			"ADFRC_PC_Tan_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		icon="iconManAT";
		backpack="adfrc_CarryAll_amcu_at";
	};
	class ADFRC_crewman_amcu: ADFRC_rifleman_amcu
	{
		scope=2;
		author="$STR_ADF_AUTHOR";
		_generalMacro="ADFRC_amcu_Crewman";
		displayName="Crewman";
		//editorPreview = "ADF_Units\ADFRC_men_amcu\preview\ADFRC_crewman_amcu.jpg";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"ADF_Units\ADFRC_men_amcu\data\uniform_amcu_co.paa"
		};
		weapons[]=
		{
			"arifle_AUG_C_black_F",
			"ADFRC_hpII",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"arifle_AUG_C_black_F",
			"ADFRC_hpII",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE",
			"SmokeShell",
			"SmokeShell"
		};
		respawnMagazines[]=
		{
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE",
			"SmokeShell",
			"SmokeShell"
		};
		linkedItems[]=
		{
			"H_HelmetCrew_I",
			"ADFRC_LPC_Tan_1",
			"adfrc_facewear_Shemagh_cbr_gatorz_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"H_HelmetCrew_I",
			"ADFRC_LPC_Tan_1",
			"adfrc_facewear_Shemagh_cbr_gatorz_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		backpack="";
	};
	/*class ADFRC_cavalryman_amcu: ADFRC_rifleman_amcu
	{
		scope=2;
		author="$STR_ADF_AUTHOR";
		_generalMacro="ADFRC_amcu_Crewman";
		displayName="Cavalryman";
		//editorPreview = "ADF_Units\ADFRC_men_amcu\preview\ADFRC_cavalryman_amcu.jpg";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"ADF_Units\ADFRC_men_amcu\data\uniform_amcu_co.paa"
		};
		weapons[]=
		{
			"ADFRC_F88SA1_eotech_laser",
			"ADFRC_hpII",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"ADFRC_F88SA1_eotech_laser",
			"ADFRC_hpII",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE",
			"SmokeShell",
			"SmokeShell"
		};
		respawnMagazines[]=
		{
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE",
			"SmokeShell",
			"SmokeShell"
		};
		linkedItems[]=
		{
			"H_Cap_headphones",
			"ADFRC_carrierLite_amcu",
			"adfrc_facewear_kondor_blk_blk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"H_Cap_headphones",
			"ADFRC_carrierLite_amcu",
			"adfrc_facewear_kondor_blk_blk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		backpack="";
	};*/
	class ADFRC_teamleader_amcu: ADFRC_rifleman_amcu
	{
		scope=2;
		author="$STR_ADF_AUTHOR";
		_generalMacro="B_Soldier_F";
		displayName="Brick Leader";
		//editorPreview = "ADF_Units\ADFRC_men_amcu\preview\ADFRC_teamleader_amcu.jpg";
		uniformClass="ADFRC_uniform_amcu_recon";
		model="\A3\characters_F\BLUFOR\b_soldier_01.p3d";
		weapons[]=
		{
			"arifle_AUG_GL_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"arifle_AUG_GL_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE",
			"SmokeShell",
			"SmokeShell"
		};
		respawnMagazines[]=
		{
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE",
			"SmokeShell",
			"SmokeShell"
		};
		linkedItems[]=
		{
			"ADFRC_teamwendy_exfil_amcu_ct_2_Aus",
			"ADFRC_PC_Tan_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ADFRC_teamwendy_exfil_amcu_ct_2_Aus",
			"ADFRC_PC_Tan_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		backpack="ADFRC_AssaultPack_TL_amcu";
		icon="iconManLeader";
	};
	class ADFRC_squadleader_amcu: ADFRC_rifleman_amcu
	{
		scope=2;
		author="$STR_ADF_AUTHOR";
		_generalMacro="B_Soldier_F";
		displayName="Section Leader";
		//editorPreview = "ADF_Units\ADFRC_men_amcu\preview\ADFRC_squadleader_amcu.jpg";
		uniformClass="ADFRC_uniform_amcu";
		model="\A3\characters_F\BLUFOR\b_soldier_03.p3d";
		weapons[]=
		{
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE",
			"SmokeShellPurple",
			"SmokeShellPurple",
			"SmokeShellRed",
			"SmokeShellRed",
			"SmokeShellOrange",
			"SmokeShellOrange"
		};
		respawnMagazines[]=
		{
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE",
			"SmokeShellPurple",
			"SmokeShellPurple",
			"SmokeShellRed",
			"SmokeShellRed",
			"SmokeShellOrange",
			"SmokeShellOrange"
		};
		linkedItems[]=
		{
			"ADFRC_teamwendy_exfil_amcu_ct_2_Aus",
			"ADFRC_PC_Tan_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ADFRC_teamwendy_exfil_amcu_ct_2_Aus",
			"ADFRC_PC_Tan_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		icon="iconManOfficer";
		backpack="";
	};
	class ADFRC_pilot_amcu: ADFRC_rifleman_amcu
	{
		scope=2;
		author="$STR_ADF_AUTHOR";
		_generalMacro="ADFRC_amcu_Pilot";
		displayName="Helicopter Pilot";
		//editorPreview = "ADF_Units\ADFRC_men_amcu\preview\ADFRC_pilot_amcu.jpg";
		weapons[]=
		{
			"ADFRC_hpII",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"ADFRC_hpII",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE",
			"SmokeShell",
			"SmokeShellRed",
			"SmokeShellPurple"
		};
		respawnMagazines[]=
		{
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE",
			"SmokeShell",
			"SmokeShellRed",
			"SmokeShellPurple"
		};
		linkedItems[]=
		{
			"H_PilotHelmetHeli_O",
			"V_TacVest_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"H_PilotHelmetHeli_O",
			"V_TacVest_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		backpack="";
	};
	class ADFRC_helicrew_amcu: ADFRC_rifleman_amcu
	{
		scope=2;
		author="$STR_ADF_AUTHOR";
		displayName="Helicopter Crew";
		//editorPreview = "ADF_Units\ADFRC_men_amcu\preview\ADFRC_pilot_amcu.jpg";
		weapons[]=
		{
			"ADFRC_hpII",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"ADFRC_hpII",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE",
			"SmokeShell",
			"SmokeShellRed",
			"SmokeShellPurple"
		};
		respawnMagazines[]=
		{
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE",
			"SmokeShell",
			"SmokeShellRed",
			"SmokeShellPurple"
		};
		linkedItems[]=
		{
			"H_CrewHelmetHeli_O",
			"V_TacVest_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"H_CrewHelmetHeli_O",
			"V_TacVest_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		backpack="";
	};
	class ADFRC_lightGunner_amcu: ADFRC_rifleman_amcu
	{
		scope=2;
		author="$STR_ADF_AUTHOR";
		_generalMacro="B_Soldier_F";
		displayName="LSW Gunner";
		//editorPreview = "ADF_Units\ADFRC_men_amcu\preview\ADFRC_lightGunner_amcu.jpg";
		uniformClass="ADFRC_uniform_amcu_recon";
		model="\A3\characters_F\BLUFOR\b_soldier_03.p3d";
		weapons[]=
		{
			"ADFRC_minimi_eotech",
			"ADFRC_hpII",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"ADFRC_minimi_eotech",
			"ADFRC_hpII",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"ADFRC_200Rnd_556_Belt_TR5",
			"ADFRC_200Rnd_556_Belt_TR5",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		respawnMagazines[]=
		{
			"ADFRC_200Rnd_556_Belt_TR5",
			"ADFRC_200Rnd_556_Belt_TR5",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		linkedItems[]=
		{
			"ADFRC_teamwendy_exfil_amcu_ct_2_Aus",
			"ADFRC_PC_Tan_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ADFRC_teamwendy_exfil_amcu_ct_2_Aus",
			"ADFRC_PC_Tan_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		backpack="ADFRC_Carryall_LSW_amcu";
		icon="iconManMG";
	};
	class ADFRC_heavyGunner_amcu: ADFRC_rifleman_amcu
	{
		scope=2;
		author="$STR_ADF_AUTHOR";
		_generalMacro="B_Soldier_F";
		displayName="General Support Machine Gunner";
		//editorPreview = "ADF_Units\ADFRC_men_amcu\preview\ADFRC_heavyGunner_amcu.jpg";
		uniformClass="ADFRC_uniform_amcu";
		model="\A3\characters_F\BLUFOR\b_soldier_03.p3d";
		weapons[]=
		{
			"ADFRC_mag58_elcan",
			"ADFRC_hpII",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"ADFRC_mag58_elcan",
			"ADFRC_hpII",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"ADFRC_150Rnd_762_Belt_TR5",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		respawnMagazines[]=
		{
			"ADFRC_150Rnd_762_Belt_TR5",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE"
		};
		linkedItems[]=
		{
			"ADFRC_teamwendy_exfil_amcu_ct_2_Aus",
			"ADFRC_PC_Tan_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ADFRC_teamwendy_exfil_amcu_ct_2_Aus",
			"ADFRC_PC_Tan_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		backpack="ADFRC_Carryall_MG_amcu";
		icon="iconManMG";
	};
	class ADFRC_heavyGunner_ass_amcu: ADFRC_rifleman_amcu
	{
		scope=2;
		author="$STR_ADF_AUTHOR";
		_generalMacro="B_Soldier_F";
		displayName="General Support Gunner Ass.";
		//editorPreview = "ADF_Units\ADFRC_men_amcu\preview\ADFRC_heavyGunner_ass_amcu.jpg";
		uniformClass="ADFRC_uniform_amcu_recon";
		model="\A3\characters_F\BLUFOR\b_soldier_03.p3d";
		linkedItems[]=
		{
			"ADFRC_teamwendy_exfil_amcu_ct_2_Aus",
			"ADFRC_PC_Tan_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ADFRC_teamwendy_exfil_amcu_ct_2_Aus",
			"ADFRC_PC_Tan_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		backpack="ADFRC_Carryall_MG_amcu";
		icon="iconMan";
	};
	/*class ADFRC_ammobearer_amcu: ADFRC_rifleman_amcu
	{
		scope=2;
		author="$STR_ADF_AUTHOR";
		_generalMacro="B_Soldier_F";
		displayName="Ammobearer";
		//editorPreview = "ADF_Units\ADFRC_men_amcu\preview\ADFRC_ammobearer_amcu.jpg";
		uniformClass="ADFRC_uniform_amcu_recon";
		model="\A3\characters_F\BLUFOR\b_soldier_03.p3d";
		weapons[]=
		{
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"arifle_AUG_black_arco_flash_F",
			"ADFRC_hpII",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE",
			"SmokeShell",
			"SmokeShell"
		};
		respawnMagazines[]=
		{
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"ADFRC_F1_GRENADE",
			"ADFRC_F1_GRENADE",
			"SmokeShell",
			"SmokeShell"
		};
		linkedItems[]=
		{
			"adfrc_ECH_amcu",
			"ADFRC_carrierLite_amcu",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"adfrc_ECH_amcu",
			"ADFRC_carrierLite_amcu",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		backpack="ADFRC_Carryall_LSW_amcu";
		icon="iconManLeader";
	};*/
	class ADFRC_rifleman_amcu_ss: ADFRC_rifleman_amcu
	{
		scope=2;
		scopeCurator=2;
		author="$STR_ADFRC_AUTHOR";
		displayName="Rifleman (Rolled Sleeve)";
		uniformClass="ADFRC_uniform_amcu_recon";
		model="\A3\characters_F\BLUFOR\b_soldier_03.p3d";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\ADF_Units\adfrc_men_amcu\data\clothing_recut_amc_u_co.paa"
		};
		hiddenSelectionsMaterials[] = {
			"\ADF_Units\adfrc_men_amcu\data\clothing1.rvmat"
		};
	};
};
class cfgWeapons
{
	class UniformItem;
	class U_B_CombatUniform_mcam;
	class U_B_CombatUniform_mcam_vest;
	class HeadGearItem;
	class H_HelmetB;
	class ADFRC_HelmetC_amcu: H_HelmetB
	{
		scope=2;
		author="$STR_ADFRC_AUTHOR";
		displayName="ADF ECH [AMCU]";
		weaponPoolAvailable=1;
		picture="\A3\characters_f\Data\UI\icon_H_HelmetB_CA.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\ADF_Units\adfrc_men_amcu\data\amcu_helmet_co.paa"
		};
	};
	class ADFRC_uniform_amcu: U_B_CombatUniform_mcam
	{
		scope=2;
		author="$STR_ADFRC_AUTHOR";
		displayName="AMCU Combat Dress (Long Sleeve)";
		picture="\ADF_Units\adfrc_men_amcu\data\icon_u_b_combatuniform_AMCU_ca.paa";
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="ADFRC_rifleman_amcu";
			containerClass="Supply20";
			mass=80;
		};
	};
	class ADFRC_uniform_amcu_recon: U_B_CombatUniform_mcam_vest
	{
		scope=2;
		author="$STR_ADFRC_AUTHOR";
		displayName="AMCU Combat Dress (Short Sleeve)";
		picture="\ADF_Units\adfrc_men_amcu\data\icon_u_b_combatuniform_AMCU_ca.paa";
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="ADFRC_rifleman_amcu_ss";
			containerClass="Supply20";
			mass=80;
		};
	};
};