class CfgPatches
{
	class ADFU_uniform_dpcu
	{
		units[]=
		{
			"ADFU_DPCU_Soldier_Base",
			"ADFU_rifleman_dpcu",
			"ADFU_engineer_dpcu",
			"ADFU_grenadier_dpcu",
			"ADFU_marksman_dpcu",
			"ADFU_medic_dpcu",
			"ADFU_riflemanAT_dpcu",
			"ADFU_crewman_dpcu",
			"ADFU_teamleader_dpcu",
			"ADFU_squadleader_dpcu",
			"ADFU_pilot_dpcu",
			"ADFU_lightGunner_dpcu",
			"ADFU_heavyGunner_dpcu",
			"ADFU_ammobearer_dpcu",
			"ADFU_ka60_dpcu",
			"ADFU_ah9_dpcu",
			"ADFU_mh9_dpcu",
			"ADFU_hunter_dpcu",
			"ADFU_hunterHMG_dpcu",
			"ADFU_hunterGMG_dpcu",
			"ADFU_AssaultPack_dpcu",
			"ADFU_Carryall_dpcu",
			"ADFU_Carryall_dpcu_diver",
			"ADFU_Carryall_dpcu_medic",
			"ADFU_Carryall_dpcu_engineer",
			"ADFU_Carryall_dpcu_at"
		};
		weapons[]=
		{
			"ADFU_HelmetC_dpcu",
			"ADFU_helmetB_dpcu",
			"ADFU_booniehat_dpcu",
			"ADFU_carrierLite_dpcu",
			"ADFU_plateCarrier_dpcu",
			"ADFU_tacticalVest_dpcu",
			"ADFU_uniform_dpcu",
			"ADFU_uniform_dpcu_recon",
			"ADFU_uniform_dpcu_medic",
			"ADFU_uniform_dpcu_tee",
			"ADFU_coveralls_dpcu"
		};
		requiredVersion=0.1;
		requiredAddons[]=
		{
			"A3_Weapons_F",
			"A3_Characters_F_BLUFOR",
			"ADFU_faction"
		};
	};
};
class CfgEditorSubcategories
{
	class ADFU_MEN_DPCU // Category class, you point to it in editorSubcategory property
	{
		displayName = "Men (DPCU)"; // Name visible in the list
	};
};
class cfgVehicles
{
	class ADFU_Soldier_base_F;
	class ADFU_DPCU_Soldier_Base: ADFU_Soldier_base_F
	{
		scope=1;
		author="$STR_ADFU_AUTHOR";
		faction="ADFU";
		editorSubcategory= "ADFU_MEN_DPCU";
		genericNames="NATOMen";
		nakedUniform="U_BasicBody";
		uniformClass="ADFU_uniform_dpcu";
		model="\A3\characters_F\BLUFOR\b_soldier_01.p3d";
		weapons[]=
		{
			"ADFU_F88SA1_elcan",
			"ADFU_weapon_hpII",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"ADFU_F88SA1_elcan",
			"ADFU_weapon_hpII",
			"Throw",
			"Put",
			"Binocular"
		};
		Items[]=
		{
			"FirstAidKit"
		};
		RespawnItems[]=
		{
			"FirstAidKit"
		};
		magazines[]=
		{
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFU_F1_GRENADE",
			"ADFU_F1_GRENADE"
		};
		respawnMagazines[]=
		{
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFU_F1_GRENADE",
			"ADFU_F1_GRENADE"
		};
		linkedItems[]=
		{
			"ADFU_HelmetC_dpcu",
			"ADFU_carrierLite_dpcu",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ADFU_HelmetC_dpcu",
			"ADFU_carrierLite_dpcu",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class ADFU_rifleman_dpcu: ADFU_DPCU_Soldier_Base
	{
		scope=2;
		author="$STR_ADFU_AUTHOR";
		_generalMacro="ADFU_rifleman_dpcu";
		displayName="Rifleman";
		vehicleClass="ADFU_MEN_DPCU";
		uniformAccessories[]={};
		uniformClass="ADFU_uniform_dpcu";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"ADFU_uniform_dpcu\data\uniform_DPCU_co.paa"
		};
		backpack="ADFU_AssaultPack_dpcu";
	};
	class ADFU_engineer_dpcu: ADFU_rifleman_dpcu
	{
		scope=2;
		author="$STR_ADFU_AUTHOR";
		_generalMacro="ADFU_engineer_dpcu";
		displayName="Combat Engineer";
		engineer=1;
		saboteur=1;
		canDeactivateMines=1;
		detectSkill=80;
		model="\A3\characters_F\BLUFOR\b_soldier_03.p3d";
		linkedItems[]=
		{
			"ADFU_helmetB_dpcu",
			"ADFU_plateCarrier_dpcu",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ADFU_helmetB_dpcu",
			"ADFU_plateCarrier_dpcu",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		backpack="ADFU_Carryall_dpcu_engineer";
		icon="iconManEngineer";
		picture="pictureRepair";
	};
	class ADFU_grenadier_dpcu: ADFU_rifleman_dpcu
	{
		scope=2;
		author="$STR_ADFU_AUTHOR";
		_generalMacro="ADFU_grenadier_dpcu";
		displayName="Grenadier";
		weapons[]=
		{
			"ADFU_F88SA1_gl_mrco",
			"ADFU_weapon_hpII",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"ADFU_F88SA1_gl_mrco",
			"ADFU_weapon_hpII",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"ADFU_F1_GRENADE",
			"ADFU_F1_GRENADE",
			"SmokeShell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell"
		};
		respawnMagazines[]=
		{
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"ADFU_F1_GRENADE",
			"ADFU_F1_GRENADE",
			"SmokeShell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell"
		};
		backpack="ADFU_Carryall_dpcu";
	};
	class ADFU_marksman_dpcu: ADFU_rifleman_dpcu
	{
		scope=2;
		author="$STR_ADFU_AUTHOR";
		_generalMacro="ADFU_marksman_dpcu";
		displayName="Marksman";
		uniformClass="ADFU_uniform_dpcu_tee";
		model="\A3\characters_F\BLUFOR\b_soldier_02.p3d";
		hiddenSelections[]=
		{
			"Camo",
			"Camo2"
		};
		hiddenSelectionsTextures[]=
		{
			"ADFU_uniform_dpcu\data\uniform_DPCU_co.paa",
			"ADFU_uniform_dpcu\data\basicbody_army_co.paa"
		};
		weapons[]=
		{
			"ADFU_sr25_ta648",
			"ADFU_weapon_hpII",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"ADFU_sr25_ta648",
			"ADFU_weapon_hpII",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"ADFU_F1_GRENADE",
			"ADFU_F1_GRENADE",
			"SmokeShell",
			"SmokeShell"
		};
		respawnMagazines[]=
		{
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"ADFU_F1_GRENADE",
			"ADFU_F1_GRENADE",
			"SmokeShell",
			"SmokeShell"
		};
		backpack="ADFU_AssaultPack_dpcu";
	};
	class ADFU_medic_dpcu: ADFU_rifleman_dpcu
	{
		scope=2;
		author="$STR_ADFU_AUTHOR";
		_generalMacro="ADFU_DPCU_Medic";
		displayName="Combat Medic";
		attendant=1;
		model="\A3\characters_F\BLUFOR\b_soldier_03.p3d";
		uniformClass="ADFU_uniform_dpcu_medic";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\ADFU_uniform_dpcu\data\uniform_DPCU_MEDIC_co.paa"
		};
		linkedItems[]=
		{
			"ADFU_HelmetC_dpcu",
			"ADFU_carrierLite_dpcu",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ADFU_HelmetC_dpcu",
			"ADFU_carrierLite_dpcu",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		icon="iconManMedic";
		backpack="ADFU_Carryall_dpcu_Medic";
	};
	class ADFU_riflemanAT_dpcu: ADFU_rifleman_dpcu
	{
		scope=2;
		author="$STR_ADFU_AUTHOR";
		_generalMacro="ADFU_DPCU_RiflemanAT";
		displayName="Rifleman AT";
		model="\A3\characters_F\BLUFOR\b_soldier_03.p3d";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\ADFU_uniform_dpcu\data\uniform_DPCU_co.paa"
		};
		weapons[]=
		{
			"ADFU_F88SA1_elcan",
			"ADFU_carlgustav_m3",
			"ADFU_weapon_hpII",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"ADFU_F88SA1_elcan",
			"ADFU_carlgustav_m3",
			"ADFU_weapon_hpII",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"ADFU_magazine_84mm_heat_551c",
			"ADFU_magazine_84mm_heat_551c",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"ADFU_F1_GRENADE",
			"ADFU_F1_GRENADE",
			"SmokeShell",
			"SmokeShellRed",
			"SmokeShellGreen",
			"SmokeShellYellow"
		};
		respawnMagazines[]=
		{
			"ADFU_magazine_84mm_heat_551c",
			"ADFU_magazine_84mm_heat_551c",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"ADFU_F1_GRENADE",
			"ADFU_F1_GRENADE",
			"SmokeShell",
			"SmokeShellRed",
			"SmokeShellGreen",
			"SmokeShellYellow"
		};
		linkedItems[]=
		{
			"ADFU_HelmetC_dpcu",
			"ADFU_carrierLite_dpcu",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ADFU_HelmetC_dpcu",
			"ADFU_carrierLite_dpcu",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		icon="iconManAT";
		backpack="ADFU_Carryall_dpcu_at";
	};
	class ADFU_crewman_dpcu: ADFU_rifleman_dpcu
	{
		scope=2;
		author="$STR_ADFU_AUTHOR";
		_generalMacro="ADFU_DPCU_Crewman";
		displayName="Cavalryman";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"ADFU_uniform_dpcu\data\uniform_DPCU_co.paa"
		};
		weapons[]=
		{
			"ADFU_F88SA1_elcan",
			"ADFU_weapon_hpII",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"ADFU_F88SA1_elcan",
			"ADFU_weapon_hpII",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"ADFU_F1_GRENADE",
			"ADFU_F1_GRENADE",
			"SmokeShell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell"
		};
		respawnMagazines[]=
		{
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"ADFU_F1_GRENADE",
			"ADFU_F1_GRENADE",
			"SmokeShell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell"
		};
		linkedItems[]=
		{
			"H_Cap_headphones",
			"ADFU_carrierLite_dpcu",
			"g_combat",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"H_Cap_headphones",
			"ADFU_carrierLite_dpcu",
			"g_combat",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class ADFU_teamleader_dpcu: ADFU_rifleman_dpcu
	{
		scope=2;
		author="$STR_ADFU_AUTHOR";
		_generalMacro="B_Soldier_F";
		displayName="Team Leader";
		uniformClass="ADFU_uniform_dpcu_recon";
		model="\A3\characters_F\BLUFOR\b_soldier_01.p3d";
		weapons[]=
		{
			"ADFU_F88SA1_elcan",
			"ADFU_weapon_hpII",
			"ADFU_weapon_m72a6",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"ADFU_F88SA1_elcan",
			"ADFU_weapon_hpII",
			"ADFU_weapon_m72a6",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"ADFU_F1_GRENADE",
			"ADFU_F1_GRENADE",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_SmokeRed_Grenade_shell",
			"1Rnd_SmokeGreen_Grenade_shell",
			"1Rnd_SmokeYellow_Grenade_shell",
			"1Rnd_SmokePurple_Grenade_shell",
			"1Rnd_SmokeBlue_Grenade_shell",
			"1Rnd_SmokeOrange_Grenade_shell"
		};
		respawnMagazines[]=
		{
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"ADFU_F1_GRENADE",
			"ADFU_F1_GRENADE",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_SmokeRed_Grenade_shell",
			"1Rnd_SmokeGreen_Grenade_shell",
			"1Rnd_SmokeYellow_Grenade_shell",
			"1Rnd_SmokePurple_Grenade_shell",
			"1Rnd_SmokeBlue_Grenade_shell",
			"1Rnd_SmokeOrange_Grenade_shell"
		};
		linkedItems[]=
		{
			"ADFU_HelmetC_dpcu",
			"ADFU_plateCarrier_dpcu",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ADFU_HelmetC_dpcu",
			"ADFU_plateCarrier_dpcu",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		backpack="ADFU_AssaultPack_dpcu";
		icon="iconManLeader";
	};
	class ADFU_squadleader_dpcu: ADFU_rifleman_dpcu
	{
		scope=2;
		author="$STR_ADFU_AUTHOR";
		_generalMacro="B_Soldier_F";
		displayName="Squad Leader";
		uniformClass="ADFU_uniform_dpcu_recon";
		model="\A3\characters_F\BLUFOR\b_soldier_03.p3d";
		weapons[]=
		{
			"ADFU_F88SA1_gl_ta648",
			"ADFU_weapon_hpII",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"ADFU_F88SA1_gl_ta648",
			"ADFU_weapon_hpII",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"ADFU_F1_GRENADE",
			"ADFU_F1_GRENADE",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_SmokeRed_Grenade_shell",
			"1Rnd_SmokeGreen_Grenade_shell",
			"1Rnd_SmokeYellow_Grenade_shell",
			"1Rnd_SmokePurple_Grenade_shell",
			"1Rnd_SmokeBlue_Grenade_shell",
			"1Rnd_SmokeOrange_Grenade_shell"
		};
		respawnMagazines[]=
		{
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"ADFU_F1_GRENADE",
			"ADFU_F1_GRENADE",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_SmokeRed_Grenade_shell",
			"1Rnd_SmokeGreen_Grenade_shell",
			"1Rnd_SmokeYellow_Grenade_shell",
			"1Rnd_SmokePurple_Grenade_shell",
			"1Rnd_SmokeBlue_Grenade_shell",
			"1Rnd_SmokeOrange_Grenade_shell"
		};
		linkedItems[]=
		{
			"ADFU_HelmetC_dpcu",
			"ADFU_plateCarrier_dpcu",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ADFU_HelmetC_dpcu",
			"ADFU_plateCarrier_dpcu",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		backpack="";
		icon="iconManLeader";
	};
	class ADFU_pilot_dpcu: ADFU_rifleman_dpcu
	{
		scope=2;
		author="$STR_ADFU_AUTHOR";
		_generalMacro="ADFU_DPCU_Pilot";
		displayName="Pilot";
		model="\A3\Characters_F\Common\coveralls.p3d";
		uniformClass="ADFU_coveralls_dpcu";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\ADFU_uniform_dpcu\data\pilotoveralls_DPCU_co.paa"
		};
		weapons[]=
		{
			"ADFU_F88SA1_elcan",
			"ADFU_weapon_hpII",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"ADFU_F88SA1_elcan",
			"ADFU_weapon_hpII",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"ADFU_F1_GRENADE",
			"ADFU_F1_GRENADE",
			"SmokeShell",
			"SmokeShellRed",
			"SmokeShellGreen",
			"SmokeShellYellow"
		};
		respawnMagazines[]=
		{
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"ADFU_F1_GRENADE",
			"ADFU_F1_GRENADE",
			"SmokeShell",
			"SmokeShellRed",
			"SmokeShellGreen",
			"SmokeShellYellow"
		};
		linkedItems[]=
		{
			"H_PilotHelmetHeli_B",
			"ADFU_tacticalVest_dpcu",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"H_PilotHelmetHeli_B",
			"ADFU_tacticalVest_dpcu",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class ADFU_lightGunner_dpcu: ADFU_rifleman_dpcu
	{
		scope=2;
		author="$STR_ADFU_AUTHOR";
		_generalMacro="B_Soldier_F";
		displayName="Light Machine Gunner";
		uniformClass="ADFU_uniform_dpcu_recon";
		model="\A3\characters_F\BLUFOR\b_soldier_03.p3d";
		weapons[]=
		{
			"ADFU_minimi",
			"ADFU_weapon_hpII",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"ADFU_minimi",
			"ADFU_weapon_hpII",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"ADFU_200Rnd_556_Belt_TR5",
			"ADFU_200Rnd_556_Belt_TR5",
			"ADFU_200Rnd_556_Belt_TR5",
			"ADFU_200Rnd_556_Belt_TR5",
			"ADFU_200Rnd_556_Belt_TR5",
			"ADFU_200Rnd_556_Belt_TR5",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"SmokeShell",
			"ADFU_F1_GRENADE",
			"ADFU_F1_GRENADE"
		};
		respawnMagazines[]=
		{
			"ADFU_200Rnd_556_Belt_TR5",
			"ADFU_200Rnd_556_Belt_TR5",
			"ADFU_200Rnd_556_Belt_TR5",
			"ADFU_200Rnd_556_Belt_TR5",
			"ADFU_200Rnd_556_Belt_TR5",
			"ADFU_200Rnd_556_Belt_TR5",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"SmokeShell",
			"ADFU_F1_GRENADE",
			"ADFU_F1_GRENADE"
		};
		linkedItems[]=
		{
			"ADFU_HelmetC_dpcu",
			"ADFU_carrierLite_dpcu",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ADFU_HelmetC_dpcu",
			"ADFU_carrierLite_dpcu",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		backpack="";
		icon="iconManLeader";
	};
	class ADFU_heavyGunner_dpcu: ADFU_rifleman_dpcu
	{
		scope=2;
		author="$STR_ADFU_AUTHOR";
		_generalMacro="B_Soldier_F";
		displayName="Heavy Machine Gunner";
		uniformClass="ADFU_uniform_dpcu_recon";
		model="\A3\characters_F\BLUFOR\b_soldier_03.p3d";
		weapons[]=
		{
			"ADFU_mag58_elcan",
			"ADFU_weapon_hpII",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"ADFU_mag58_elcan",
			"ADFU_weapon_hpII",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"ADFU_150Rnd_762_Belt_TR5",
			"ADFU_150Rnd_762_Belt_TR5",
			"ADFU_150Rnd_762_Belt_TR5",
			"ADFU_150Rnd_762_Belt_TR5",
			"ADFU_150Rnd_762_Belt_TR5",
			"ADFU_150Rnd_762_Belt_TR5",
			"ADFU_150Rnd_762_Belt_TR5",
			"ADFU_150Rnd_762_Belt_TR5",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"SmokeShell",
			"ADFU_F1_GRENADE",
			"ADFU_F1_GRENADE"
		};
		respawnMagazines[]=
		{
			"ADFU_150Rnd_762_Belt_TR5",
			"ADFU_150Rnd_762_Belt_TR5",
			"ADFU_150Rnd_762_Belt_TR5",
			"ADFU_150Rnd_762_Belt_TR5",
			"ADFU_150Rnd_762_Belt_TR5",
			"ADFU_150Rnd_762_Belt_TR5",
			"ADFU_150Rnd_762_Belt_TR5",
			"ADFU_150Rnd_762_Belt_TR5",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"SmokeShell",
			"ADFU_F1_GRENADE",
			"ADFU_F1_GRENADE"
		};
		linkedItems[]=
		{
			"ADFU_HelmetC_dpcu",
			"ADFU_carrierLite_dpcu",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ADFU_HelmetC_dpcu",
			"ADFU_carrierLite_dpcu",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		backpack="";
		icon="iconManLeader";
	};
	class ADFU_ammobearer_dpcu: ADFU_rifleman_dpcu
	{
		scope=2;
		author="$STR_ADFU_AUTHOR";
		_generalMacro="B_Soldier_F";
		displayName="Ammobearer";
		uniformClass="ADFU_uniform_dpcu_recon";
		model="\A3\characters_F\BLUFOR\b_soldier_03.p3d";
		weapons[]=
		{
			"ADFU_F88SA1_elcan",
			"ADFU_weapon_hpII",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"ADFU_F88SA1_elcan",
			"ADFU_weapon_hpII",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"ADFU_F1_GRENADE",
			"ADFU_F1_GRENADE",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_SmokeRed_Grenade_shell",
			"1Rnd_SmokeGreen_Grenade_shell",
			"1Rnd_SmokeYellow_Grenade_shell",
			"1Rnd_SmokePurple_Grenade_shell",
			"1Rnd_SmokeBlue_Grenade_shell",
			"1Rnd_SmokeOrange_Grenade_shell"
		};
		respawnMagazines[]=
		{
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"ADFU_30Rnd_aug",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"ADFU_F1_GRENADE",
			"ADFU_F1_GRENADE",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_SmokeRed_Grenade_shell",
			"1Rnd_SmokeGreen_Grenade_shell",
			"1Rnd_SmokeYellow_Grenade_shell",
			"1Rnd_SmokePurple_Grenade_shell",
			"1Rnd_SmokeBlue_Grenade_shell",
			"1Rnd_SmokeOrange_Grenade_shell"
		};
		linkedItems[]=
		{
			"ADFU_HelmetC_dpcu",
			"ADFU_plateCarrier_dpcu",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ADFU_HelmetC_dpcu",
			"ADFU_plateCarrier_dpcu",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		backpack="ADFU_Carryall_dpcu";
		icon="iconManLeader";
	};
	class O_Heli_Light_02_unarmed_F;
	class B_Heli_Light_01_armed_F;
	class B_Heli_Light_01_F;
	class B_MRAP_01_F;
	class B_MRAP_01_gmg_F;
	class B_MRAP_01_hmg_F;
	class ADFU_ka60_dpcu: O_Heli_Light_02_unarmed_F
	{
		scope=1;
		side=1;
		author="$STR_ADFU_AUTHOR";
		faction="ADFU";
		vehicleClass="AIR";
		displayName="KA-60 (DPCU)";
		crew="ADFU_pilot_dpcu";
		typicalCargo[]={};
		attendant=1;
		hiddenSelections[]=
		{
			"camo1"
		};
		hiddenSelectionsTextures[]=
		{
			"\ADFU_uniform_dpcu\data\ka60_co.paa"
		};
	};
	class ADFU_ah9_dpcu: B_Heli_Light_01_armed_F
	{
		scope=2;
		side=1;
		author="$STR_ADFU_AUTHOR";
		faction="ADFU";
		vehicleClass="AIR";
		displayName="AH-9 (DPCU)";
		crew="ADFU_pilot_dpcu";
		typicalCargo[]=
		{
			"ADFU_pilot_dpcu"
		};
		attendant=1;
		hiddenSelections[]=
		{
			"camo1"
		};
		hiddenSelectionsTextures[]=
		{
			"\ADFU_uniform_dpcu\data\ah9_co.paa"
		};
	};
	class ADFU_mh9_dpcu: B_Heli_Light_01_F
	{
		scope=2;
		side=1;
		author="$STR_ADFU_AUTHOR";
		faction="ADFU";
		vehicleClass="AIR";
		displayName="MH-9 (DPCU)";
		crew="ADFU_pilot_dpcu";
		typicalCargo[]=
		{
			"ADFU_teamLeader_dpcu",
			"ADFU_rifleman_dpcu",
			"ADFU_engineer_dpcu",
			"ADFU_medic_dpcu",
			"ADFU_rifleman_dpcu"
		};
		attendant=1;
		hiddenSelections[]=
		{
			"camo1"
		};
		hiddenSelectionsTextures[]=
		{
			"\ADFU_uniform_dpcu\data\ah9_co.paa"
		};
	};
	class ADFU_hunter_dpcu: B_MRAP_01_F
	{
		scope=2;
		side=1;
		author="$STR_ADFU_AUTHOR";
		faction="ADFU";
		vehicleClass="CAR";
		displayName="M-ATV (DPCU)";
		crew="ADFU_crewman_dpcu";
		typicalCargo[]=
		{
			"ADFU_teamLeader_dpcu",
			"ADFU_engineer_dpcu",
			"ADFU_medic_dpcu"
		};
		attendant=1;
		hiddenSelectionsTextures[]=
		{
			"\ADFU_uniform_dpcu\data\hunter_co.paa",
			"\ADFU_uniform_dpcu\data\hunter_back_co.paa",
			""
		};
	};
	class ADFU_hunterHMG_dpcu: B_MRAP_01_hmg_F
	{
		scope=2;
		side=1;
		author="$STR_ADFU_AUTHOR";
		faction="ADFU";
		vehicleClass="CAR";
		displayName="M-ATV HMG (DPCU)";
		crew="ADFU_crewman_dpcu";
		typicalCargo[]=
		{
			"ADFU_teamLeader_dpcu",
			"ADFU_engineer_dpcu",
			"ADFU_medic_dpcu"
		};
		attendant=1;
		hiddenSelectionsTextures[]=
		{
			"\ADFU_uniform_dpcu\data\hunter_co.paa",
			"\ADFU_uniform_dpcu\data\hunter_back_co.paa",
			"\ADFU_uniform_dpcu\data\crows_co.paa",
			""
		};
	};
	class ADFU_hunterGMG_dpcu: B_MRAP_01_gmg_F
	{
		scope=2;
		side=1;
		author="$STR_ADFU_AUTHOR";
		faction="ADFU";
		vehicleClass="CAR";
		displayName="M-ATV GMG (DPCU)";
		crew="ADFU_crewman_dpcu";
		typicalCargo[]=
		{
			"ADFU_teamLeader_dpcu",
			"ADFU_engineer_dpcu",
			"ADFU_medic_dpcu"
		};
		attendant=1;
		hiddenSelectionsTextures[]=
		{
			"\ADFU_uniform_dpcu\data\hunter_co.paa",
			"\ADFU_uniform_dpcu\data\hunter_back_co.paa",
			"\ADFU_uniform_dpcu\data\crows_co.paa",
			""
		};
	};
	class B_Carryall_Base;
	class B_AssaultPack_blk;
	class ADFU_AssaultPack_dpcu: B_AssaultPack_blk
	{
		scope=2;
		author="$STR_ADFU_AUTHOR";
		displayName="ADF Assault Pack (DPCU)";
		hiddenSelectionsTextures[]=
		{
			"\ADFU_uniform_dpcu\data\assaultpack_DPCU_co.paa"
		};
	};
	class ADFU_Carryall_dpcu: B_Carryall_Base
	{
		scope=2;
		author="$STR_ADFU_AUTHOR";
		displayName="ADF Carryall (DPCU)";
		hiddenSelectionsTextures[]=
		{
			"\ADFU_uniform_dpcu\data\carryall_DPCU_co.paa"
		};
		class TransportItems
		{
			class _xx_ADFU_booniehat_dpcu
			{
				name="ADFU_booniehat_dpcu";
				count=1;
			};
		};
		class TransportMagazines
		{
			class _xx_ADFU_30Rnd_aug
			{
				magazine="ADFU_30Rnd_aug";
				count=5;
			};
			class _xx_ADFU_F1_GRENADE
			{
				magazine="ADFU_F1_GRENADE";
				count=2;
			};
			class _xx_SmokeShell
			{
				magazine="SmokeShell";
				count=1;
			};
			class _xx_SmokeShellOrange
			{
				magazine="SmokeShellRed";
				count=1;
			};
		};
	};
	class ADFU_Carryall_dpcu_diver: ADFU_Carryall_dpcu
	{
		scope=2;
		author="$STR_ADFU_AUTHOR";
		displayName="ADF Diver Carryall (DPCU)";
		hiddenSelectionsTextures[]=
		{
			"\ADFU_uniform_dpcu\data\carryall_DPCU_co.paa"
		};
		class TransportItems
		{
			class _xx_ADFU_helmetB_dpcu
			{
				name="ADFU_helmetB_dpcu";
				count=1;
			};
			class _xx_ADFU_booniehat_dpcu
			{
				name="ADFU_booniehat_dpcu";
				count=1;
			};
			class _xx_ADFU_carrierLite_dpcu
			{
				name="ADFU_carrierLite_dpcu";
				count=1;
			};
			class _xx_ADFU_uniform_dpcu
			{
				name="ADFU_uniform_dpcu";
				count=1;
			};
		};
	};
	class ADFU_Carryall_dpcu_medic: ADFU_Carryall_dpcu
	{
		scope=2;
		author="$STR_ADFU_AUTHOR";
		displayName="ADF Carryall Medic (DPCU)";
		hiddenSelectionsTextures[]=
		{
			"\ADFU_uniform_dpcu\data\carryall_DPCU_co.paa"
		};
		class TransportItems
		{
			class _xx_ADFU_booniehat_dpcu
			{
				name="ADFU_booniehat_dpcu";
				count=1;
			};
			class _xx_Medikit
			{
				name="Medikit";
				count=1;
			};
			class _xx_FirstAidKit
			{
				name="FirstAidKit";
				count=10;
			};
		};
	};
	class ADFU_Carryall_dpcu_engineer: B_Carryall_Base
	{
		scope=2;
		author="$STR_ADFU_AUTHOR";
		displayName="ADF Carryall Engineer (DPCU)";
		hiddenSelectionsTextures[]=
		{
			"\ADFU_uniform_dpcu\data\carryall_DPCU_co.paa"
		};
		class TransportItems
		{
			class _xx_ADFU_booniehat_dpcu
			{
				name="ADFU_booniehat_dpcu";
				count=1;
			};
			class _xx_Toolkit
			{
				name="Toolkit";
				count=1;
			};
		};
	};
	class ADFU_Carryall_dpcu_at: B_Carryall_Base
	{
		scope=2;
		author="$STR_ADFU_AUTHOR";
		displayName="ADF Carryall AT (DPCU)";
		hiddenSelectionsTextures[]=
		{
			"\ADFU_uniform_dpcu\data\carryall_DPCU_co.paa"
		};
		class TransportItems
		{
			class _xx_ADFU_booniehat_dpcu
			{
				name="ADFU_booniehat_dpcu";
				count=1;
			};
			class _xx_Toolkit
			{
				name="Toolkit";
				count=1;
			};
		};
		class TransportMagazines
		{
			class _xx_ADFU_30Rnd_aug
			{
				magazine="ADFU_30Rnd_aug";
				count=5;
			};
			class _xx_ADFU_F1_GRENADE
			{
				magazine="ADFU_F1_GRENADE";
				count=2;
			};
			class _xx_ADFU_magazine_84mm_heat_551c
			{
				magazine="ADFU_magazine_84mm_heat_551c";
				count=2;
			};
			class _xx_ADFU_magazine_84mm_heat_751
			{
				magazine="ADFU_magazine_84mm_heat_551c";
				count=2;
			};
		};
	};
};
class cfgWeapons
{
	class ItemCore;
	class HeadGearItem;
	class UniformItem;
	class ItemInfo;
	class VestItem;
	class H_HelmetIA;
	class H_HelmetB;
	class H_HelmetCrew_I;
	class H_Booniehat_tan;
	class ADFU_HelmetC_dpcu: H_HelmetIA
	{
		scope=2;
		author="$STR_ADFU_AUTHOR";
		displayName="ADF Helmet Canvas (DPCU)";
		weaponPoolAvailable=1;
		picture="\A3\characters_f\Data\UI\icon_H_HelmetB_CA.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\ADFU_uniform_dpcu\data\DPCU_helmet_co.paa"
		};
	};
	class ADFU_helmetB_dpcu: H_HelmetB
	{
		scope=2;
		author="$STR_ADFU_AUTHOR";
		displayName="ADF Helmet Ballistic (DPCU)";
		picture="\A3\characters_f\Data\UI\icon_H_HelmetB_CA.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\ADFU_uniform_dpcu\data\DPCU_helmet_us_co.paa"
		};
	};
	class ADFU_booniehat_dpcu: H_Booniehat_tan
	{
		scope=2;
		author="$STR_ADFU_AUTHOR";
		displayName="ADF Boonie (DPCU)";
		picture="\A3\characters_f\Data\UI\icon_H_HelmetB_CA.paa";
		model="\A3\Characters_F\common\booniehat";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\ADFU_uniform_dpcu\data\booniehat_DPCU_co.paa"
		};
	};
	class V_PlateCarrier1_blk;
	class V_PlateCarrierH_CTRG;
	class V_TacVest_blk;
	class ADFU_carrierLite_dpcu: V_PlateCarrier1_blk
	{
		scope=2;
		author="$STR_ADFU_AUTHOR";
		displayName="ADF Carrier Lite (DPCU)";
		model="\A3\Characters_F_EPA\BLUFOR\equip_b_vest_kerry";
		picture="\ADFU_uniform_dpcu\data\icon_DPCU_Vest_ca.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\ADFU_uniform_dpcu\data\vests_rgr_DPCU_co.paa"
		};
		class ItemInfo: ItemInfo
		{
			uniformModel="\A3\Characters_F_EPA\BLUFOR\equip_b_vest_kerry";
			containerClass="Supply140";
			mass=60;
			armor="5*0.8";
			passThrough=0.40000001;
			hiddenSelections[]=
			{
				"camo"
			};
		};
	};
	class ADFU_plateCarrier_dpcu: V_PlateCarrierH_CTRG
	{
		scope=2;
		author="$STR_ADFU_AUTHOR";
		displayName="ADF Carrier Rig (DPCU)";
		picture="\ADFU_uniform_dpcu\data\icon_DPCU_Vest_ca.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\ADFU_uniform_dpcu\data\vests_rgr_DPCU_co.paa"
		};
	};
	class ADFU_tacticalVest_dpcu: V_TacVest_blk
	{
		scope=2;
		author="$STR_ADFU_AUTHOR";
		displayName="ADF Tactical Vest (DPCU)";
		picture="\ADFU_uniform_dpcu\data\icon_DPCU_Vest_ca.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\ADFU_uniform_dpcu\data\pilotvest_DPCU_co.paa"
		};
	};
	class U_B_CombatUniform_mcam;
	class U_B_CombatUniform_mcam_vest;
	class U_B_CombatUniform_mcam_tee;
	class U_B_CombatUniform_mcam_worn;
	class V_RebreatherB;
	class ADFU_uniform_dpcu: U_B_CombatUniform_mcam
	{
		scope=2;
		author="$STR_ADFU_AUTHOR";
		displayName="Disruptive Pattern Combat Uniform (Long Sleeve)";
		picture="\ADFU_uniform_dpcu\data\icon_u_b_combatuniform_DPCU_ca.paa";
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="ADFU_rifleman_dpcu";
			containerClass="Supply20";
			mass=80;
		};
	};
	class ADFU_uniform_dpcu_recon: U_B_CombatUniform_mcam_vest
	{
		scope=2;
		author="$STR_ADFU_AUTHOR";
		displayName="Disruptive Pattern Combat Uniform (Short Sleeve)";
		picture="\ADFU_uniform_dpcu\data\icon_u_b_combatuniform_DPCU_ca.paa";
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="ADFU_squadleader_dpcu";
			containerClass="Supply20";
			mass=80;
		};
	};
	class ADFU_uniform_dpcu_medic: ADFU_uniform_dpcu
	{
		scope=2;
		author="$STR_ADFU_AUTHOR";
		displayName="Disruptive Pattern Combat Uniform (Medic)";
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="ADFU_medic_dpcu";
			containerClass="Supply20";
			mass=80;
		};
	};
	class ADFU_uniform_dpcu_tee: ADFU_uniform_dpcu
	{
		scope=2;
		author="$STR_ADFU_AUTHOR";
		displayName="Disruptive Pattern Combat Uniform (Tee)";
		picture="\ADFU_uniform_dpcu\data\icon_u_b_combatuniform_DPCU_ca.paa";
		model="\A3\characters_F\BLUFOR\b_soldier_02.p3d";
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="ADFU_marksman_dpcu";
			containerClass="Supply20";
			mass=80;
		};
	};
	class ADFU_coveralls_dpcu: ADFU_uniform_dpcu
	{
		scope=2;
		author="$STR_ADFU_AUTHOR";
		displayName="Army Aviation Coveralls (DPCU)";
		model="\A3\Characters_F\Common\coveralls.p3d";
		class ItemInfo: UniformItem
		{
			uniformModel="\A3\Characters_F\Common\coveralls";
			uniformClass="ADFU_pilot_dpcu";
			containerClass="Supply20";
			mass=80;
		};
	};
};
class CfgGroups
{
	class West
	{
		name="BLUFOR";
		side=1;
		class ADF
		{
			name="ADF";
			class Infantry
			{
				name="Infantry";
				class ADFU_InfSquad_DPCU
				{
					faction="ADFU";
					author="$STR_ADFU_AUTHOR";
					name="Rifle Squad (DPCU)";
					side=1;
					class Unit0
					{
						side=1;
						vehicle="ADFU_squadleader_dpcu";
						rank="LIEUTENANT";
						position[]={0,-7.5,0};
					};
					class Unit1
					{
						side=1;
						vehicle="ADFU_teamleader_dpcu";
						rank="SERGEANT";
						position[]={5,0,0};
					};
					class Unit2
					{
						side=1;
						vehicle="ADFU_lightgunner_dpcu";
						rank="CORPORAL";
						position[]={-5,0,0};
					};
					class Unit3
					{
						side=1;
						vehicle="ADFU_riflemanAT_dpcu";
						rank="PRIVATE";
						position[]={10,-5,0};
					};
					class Unit4
					{
						side=1;
						vehicle="ADFU_medic_dpcu";
						rank="PRIVATE";
						position[]={-10,-5,0};
					};
					class Unit5
					{
						side=1;
						vehicle="ADFU_lightgunner_dpcu";
						rank="PRIVATE";
						position[]={15,-10,0};
					};
					class Unit6
					{
						side=1;
						vehicle="ADFU_marksman_dpcu";
						rank="CORPORAL";
						position[]={-15,-10,0};
					};
					class Unit7
					{
						side=1;
						vehicle="ADFU_rifleman_dpcu";
						rank="PRIVATE";
						position[]={0,5,0};
					};
				};
				class InfTeam_DPCU
				{
					faction="ADFU";
					author="$STR_ADFU_AUTHOR";
					name="Fire Team (DPCU)";
					side=1;
					class Unit0
					{
						side=1;
						vehicle="ADFU_teamleader_dpcu";
						rank="SERGEANT";
						position[]={0,0,0};
					};
					class Unit1
					{
						side=1;
						vehicle="ADFU_lightGunner_dpcu";
						rank="CORPORAL";
						position[]={0,-5,0};
					};
					class Unit2
					{
						side=1;
						vehicle="ADFU_marksman_dpcu";
						rank="PRIVATE";
						position[]={0,-10,0};
					};
					class Unit3
					{
						side=1;
						vehicle="ADFU_medic_dpcu";
						rank="PRIVATE";
						position[]={0,-15,0};
					};
				};
				class ADFU_SupportTeam_DPCU
				{
					faction="ADF";
					side=1;
					author="$STR_ADFU_AUTHOR";
					name="Support Team (DPCU)";
					class Unit0
					{
						position[]={0,0,0};
						rank="SERGEANT";
						side=1;
						vehicle="ADFU_teamleader_dpcu";
					};
					class Unit1
					{
						position[]={5,-5,0};
						rank="CORPORAL";
						side=1;
						vehicle="ADFU_heavygunner_dpcu";
					};
					class Unit2
					{
						position[]={-5,-5,0};
						rank="PRIVATE";
						side=1;
						vehicle="ADFU_heavygunner_dpcu";
					};
					class Unit3
					{
						position[]={10,-10,0};
						rank="PRIVATE";
						side=1;
						vehicle="ADFU_ammobearer_dpcu";
					};
				};
			};
		};
	};
};
