class CfgPatches
{
	class ADFRC_uniform_dpdu
	{
		units[]=
		{
			"ADFRC_soldier_base_dpdu",
			"ADFRC_rifleman_dpdu",
			"ADFRC_grenadier_dpdu",
			"ADFRC_marksman_dpdu",
			"ADFRC_medic_dpdu",
			"ADFRC_riflemanAT_dpdu",
			"ADFRC_engineer_dpdu",
			"ADFRC_explosive_dpdu",
			"ADFRC_helicopterPilot_dpdu",
			"ADFRC_teamleader_dpdu",
			"ADFRC_squadleader_dpdu",
			"ADFRC_lightGunner_dpdu",
			"ADFRC_heavyGunner_dpdu",
			"ADFRC_carryall_dpdu",
			"ADFRC_carryall_dpdu_medic",
			"ADFRC_carryall_dpdu_engineer",
			"ADFRC_carryall_dpdu_at"
		};
		weapons[]=
		{
			"ADFRC_booniehat_dpdu",
			"ADFRC_helmetB_dpdu",
			"ADFRC_uniform_dpdu",
			"ADFRC_uniform_dpdu_medic",
			"ADFRC_uniform_dpdu_recon",
			"ADFRC_uniform_dpdu_pilot",
			"ADFRC_carrierlite_dpdu",
			"ADFRC_tacticalvest_dpdu"
		};
		requiredVersion=0.1;
		requiredAddons[]=
		{
			"A3_Weapons_F",
			"A3_Characters_F",
			"A3_Characters_F_BLUFOR",
			"ADF_Weapons",
			"ADF_Gear",
			"ADF_Core"
		};
	};
};
class CfgEditorSubcategories
{
	class ADFRC_MEN_DPDU // Category class, you point to it in editorSubcategory property
	{
		displayName =$STR_ADF_MEN_DPDU; // Name visible in the list
	};
};
class cfgVehicles
{
	class ADFRC_Soldier_base_F;
	class I_Soldier_base_F;
	class ADFRC_soldier_base_dpdu: ADFRC_Soldier_base_F
	{
		scope=1;
		_generalMacro="ADFRC_uniform_dpdu_Base";
		faction="ADF";
		editorSubcategory=$STR_ADF_MEN_DPDU;
		vehicleClass=$STR_ADF_MEN_DPDU;
		author=$STR_ADF_AUTHOR;
		genericNames="NATOMen";
		nakedUniform="U_BasicBody";
		uniformClass="U_B_CombatUniform_mcam_vest";
		weapons[]=
		{
			"ADFRC_WP_M4A5_KAC_EXPS3",
			"adfrc_usp",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"ADFRC_WP_M4A5_KAC_EXPS3",
			"adfrc_usp",
			"Throw",
			"Put",
			"Binocular"
		};
		Items[]=
		{
			"FirstAidKit"
		};
		RespawnItems[]=
		{
			"FirstAidKit"
		};
		magazines[]=
		{
			"ADFRC_30Rnd_STANAG_mixed",
			"ADFRC_30Rnd_STANAG_mixed",
			"ADFRC_30Rnd_STANAG_mixed",
			"ADFRC_30Rnd_STANAG_mixed",
			"ADFRC_30Rnd_STANAG_mixed",
			"ADFRC_30Rnd_STANAG_mixed",
			"ADFRC_30Rnd_STANAG_mixed",
			"ADFRC_30Rnd_STANAG_mixed",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_f1_grenade",
			"ADFRC_f1_grenade"
		};
		respawnMagazines[]=
		{
			"ADFRC_30Rnd_STANAG_mixed",
			"ADFRC_30Rnd_STANAG_mixed",
			"ADFRC_30Rnd_STANAG_mixed",
			"ADFRC_30Rnd_STANAG_mixed",
			"ADFRC_30Rnd_STANAG_mixed",
			"ADFRC_30Rnd_STANAG_mixed",
			"ADFRC_30Rnd_STANAG_mixed",
			"ADFRC_30Rnd_STANAG_mixed",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_f1_grenade",
			"ADFRC_f1_grenade"
		};
		linkedItems[]=
		{
			"adfrc_ECH_DPDU",
			"ADFRC_PC_Tan_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"adfrc_ECH_DPDU",
			"ADFRC_carrierlite_dpdu",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class ADFRC_rifleman_dpdu: ADFRC_soldier_base_dpdu
	{
		scope=1;
		scopeCurator=1;
		editorSubcategory="ADFRC_MEN_DPDU";
		_generalMacro="B_Soldier_F";
		displayName="Commando";
		editorPreview = "\ADF_Units\old\ADFRC_men_dpdu\preview\ADFRC_rifleman_dpdu.jpg";
		author=$STR_ADF_AUTHOR;
		uniformAccessories[]={};
		nakedUniform="U_BasicBody";
		uniformClass="ADFRC_uniform_dpdu";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\ADF_Units\old\ADFRC_men_dpdu\data\uniform_DPDU_CO.paa"
		};
		backpack="ADFRC_kitbag_2cdo";
	};
	class ADFRC_grenadier_dpdu: ADFRC_rifleman_dpdu
	{
		author=$STR_ADF_AUTHOR;
		uniformClass="ADFRC_uniform_dpdu_recon";
		model="\A3\characters_F\BLUFOR\b_soldier_03.p3d";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\ADF_Units\old\ADFRC_men_dpdu\data\uniform_DPDU_CO.paa"
		};
		displayName="Grenadier";
		editorPreview = "\ADF_Units\old\ADFRC_men_dpdu\preview\ADFRC_grenadier_dpdu.jpg";
		icon="iconManExplosive";
		weapons[]=
		{
			"ADFRC_WP_M4A5_KAC_ACOG",
			"adfrc_usp",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"ADFRC_WP_M4A5_KAC_ACOG",
			"adfrc_usp",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"ADFRC_30Rnd_STANAG_mixed",
			"ADFRC_30Rnd_STANAG_mixed",
			"ADFRC_30Rnd_STANAG_mixed",
			"ADFRC_30Rnd_STANAG_mixed",
			"ADFRC_30Rnd_STANAG_mixed",
			"ADFRC_30Rnd_STANAG_mixed",
			"ADFRC_30Rnd_STANAG_mixed",
			"ADFRC_30Rnd_STANAG_mixed",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_f1_grenade",
			"ADFRC_f1_grenade"
		};
		respawnMagazines[]=
		{
			"ADFRC_30Rnd_STANAG_mixed",
			"ADFRC_30Rnd_STANAG_mixed",
			"ADFRC_30Rnd_STANAG_mixed",
			"ADFRC_30Rnd_STANAG_mixed",
			"ADFRC_30Rnd_STANAG_mixed",
			"ADFRC_30Rnd_STANAG_mixed",
			"ADFRC_30Rnd_STANAG_mixed",
			"ADFRC_30Rnd_STANAG_mixed",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_f1_grenade",
			"ADFRC_f1_grenade"
		};
		linkedItems[]=
		{
			"adfrc_ECH_DPDU",
			"ADFRC_PC_Tan_7",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"adfrc_ECH_DPDU",
			"ADFRC_PC_Tan_7",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		backpack="ADFRC_kitbag_tan_GL";
	};
	class ADFRC_marksman_dpdu: ADFRC_rifleman_dpdu
	{
		author=$STR_ADF_AUTHOR;
		uniformClass="ADFRC_uniform_dpdu_recon";
		model="\A3\characters_F\BLUFOR\b_soldier_03.p3d";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\ADF_Units\old\ADFRC_men_dpdu\data\uniform_DPDU_CO.paa"
		};
		displayName="Designated Marksman";
		editorPreview = "\ADF_Units\old\ADFRC_men_dpdu\preview\ADFRC_marksman_dpdu.jpg";
		weapons[]=
		{
			"ADFRC_hk417_sand_army",
			"adfrc_usp",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"ADFRC_hk417_sand_army",
			"adfrc_usp",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_f1_grenade",
			"ADFRC_f1_grenade"
		};
		respawnMagazines[]=
		{
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_f1_grenade",
			"ADFRC_f1_grenade"
		};
		linkedItems[]=
		{
			"adfrc_ECH_DPDU",
			"ADFRC_carrierlite_dpdu",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"adfrc_ECH_DPDU",
			"ADFRC_carrierlite_dpdu",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class ADFRC_medic_dpdu: ADFRC_rifleman_dpdu
	{
		author=$STR_ADF_AUTHOR;
		scope=1;
		displayName="Commando Medic";
		editorPreview = "\ADF_Units\old\ADFRC_men_dpdu\preview\ADFRC_medic_dpdu.jpg";
		attendant=1;
		model="\A3\characters_F\BLUFOR\b_soldier_01.p3d";
		uniformAccessories[]={};
		uniformClass="ADFRC_uniform_dpdu_medic";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\ADF_Units\old\ADFRC_men_dpdu\data\uniform_DPDU_MEDIC_CO.paa"
		};
		linkedItems[]=
		{
			"adfrc_ECH_MEDIC_Snake",
			"ADFRC_PC_Tan_6",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"adfrc_ECH_MEDIC_Snake",
			"ADFRC_PC_Tan_6",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		icon="iconManMedic";
		backpack="ADFRC_kitbag_tan_medic";
		picture="pictureHeal";
	};
	class ADFRC_riflemanAT_dpdu: ADFRC_rifleman_dpdu
	{
		author=$STR_ADF_AUTHOR;
		uniformClass="ADFRC_uniform_dpdu_recon";
		model="\A3\characters_F\BLUFOR\b_soldier_03.p3d";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\ADF_Units\old\ADFRC_men_dpdu\data\uniform_DPDU_CO.paa"
		};
		displayName="AT Gunner";
		editorPreview = "\ADF_Units\old\ADFRC_men_dpdu\preview\ADFRC_riflemanAT_dpdu.jpg";
		weapons[]=
		{
			"ADFRC_WP_M4A5_KAC_EXPS3",
			"ADFRC_carlgustav_m3",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"ADFRC_WP_M4A5_KAC_EXPS3",
			"ADFRC_carlgustav_m3",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"ADFRC_30Rnd_STANAG_mixed",
			"ADFRC_30Rnd_STANAG_mixed",
			"ADFRC_30Rnd_STANAG_mixed",
			"ADFRC_30Rnd_STANAG_mixed",
			"ADFRC_30Rnd_STANAG_mixed",
			"ADFRC_30Rnd_STANAG_mixed",
			"ADFRC_30Rnd_STANAG_mixed",
			"ADFRC_30Rnd_STANAG_mixed",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_f1_grenade",
			"ADFRC_f1_grenade"
		};
		respawnMagazines[]=
		{
			"ADFRC_30Rnd_STANAG_mixed",
			"ADFRC_30Rnd_STANAG_mixed",
			"ADFRC_30Rnd_STANAG_mixed",
			"ADFRC_30Rnd_STANAG_mixed",
			"ADFRC_30Rnd_STANAG_mixed",
			"ADFRC_30Rnd_STANAG_mixed",
			"ADFRC_30Rnd_STANAG_mixed",
			"ADFRC_30Rnd_STANAG_mixed",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_f1_grenade",
			"ADFRC_f1_grenade"
		};
		linkedItems[]=
		{
			"adfrc_ECH_DPDU",
			"ADFRC_PC_Tan_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"adfrc_ECH_DPDU",
			"ADFRC_PC_Tan_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		icon="iconManAT";
		backpack="ADFRC_kitbag_tan_at";
	};
	class ADFRC_engineer_dpdu: ADFRC_rifleman_dpdu
	{
		author=$STR_ADF_AUTHOR;
		displayName="Commando Engineer";
		editorPreview = "\ADF_Units\old\ADFRC_men_dpdu\preview\ADFRC_engineer_dpdu.jpg";
		engineer=1;
		saboteur=1;
		canDeactivateMines=1;
		detectSkill=80;
		linkedItems[]=
		{
			"adfrc_ECH_DPDU",
			"ADFRC_PC_Tan_6",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"adfrc_ECH_DPDU",
			"ADFRC_PC_Tan_6",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		backpack="ADFRC_kitbag_tan_eng";
		icon="iconManEngineer";
		picture="pictureRepair";
	};
	class ADFRC_explosive_dpdu: ADFRC_rifleman_dpdu
	{
		author=$STR_ADF_AUTHOR;
		displayName="Breacher";
		editorPreview = "\ADF_Units\old\ADFRC_men_dpdu\preview\ADFRC_explosive_dpdu.jpg";
		saboteur=1;
		canDeactivateMines=1;
		detectSkill=80;
		magazines[]=
		{
			"ADFRC_30Rnd_STANAG_mixed",
			"ADFRC_30Rnd_STANAG_mixed",
			"ADFRC_30Rnd_STANAG_mixed",
			"ADFRC_30Rnd_STANAG_mixed",
			"ADFRC_30Rnd_STANAG_mixed",
			"ADFRC_30Rnd_STANAG_mixed",
			"ADFRC_30Rnd_STANAG_mixed",
			"ADFRC_30Rnd_STANAG_mixed",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_f1_grenade",
			"ADFRC_f1_grenade",
			"ADFRC_f1_grenade",
			"ADFRC_f1_grenade"
		};
		respawnMagazines[]=
		{
			"ADFRC_30Rnd_STANAG_mixed",
			"ADFRC_30Rnd_STANAG_mixed",
			"ADFRC_30Rnd_STANAG_mixed",
			"ADFRC_30Rnd_STANAG_mixed",
			"ADFRC_30Rnd_STANAG_mixed",
			"ADFRC_30Rnd_STANAG_mixed",
			"ADFRC_30Rnd_STANAG_mixed",
			"ADFRC_30Rnd_STANAG_mixed",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_f1_grenade",
			"ADFRC_f1_grenade",
			"ADFRC_f1_grenade",
			"ADFRC_f1_grenade"
		};
		linkedItems[]=
		{
			"adfrc_ECH_DPDU",
			"ADFRC_carrierlite_dpdu",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"adfrc_ECH_DPDU",
			"ADFRC_carrierlite_dpdu",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		backpack="ADFRC_kitbag_tan_exp";
		icon="iconManExplosive";
	};
	class ADFRC_helicopterPilot_dpdu: ADFRC_rifleman_dpdu
	{
		author=$STR_ADF_AUTHOR;
		scope=1;
		displayName="Helicopter Pilot";
		editorPreview = "\ADF_Units\old\ADFRC_men_dpdu\preview\ADFRC_helicopterPilot_dpdu.jpg";
		model="\A3\Characters_F\Common\coveralls.p3d";
		uniformAccessories[]={};
		uniformClass="ADFRC_uniform_dpdu_pilot";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\ADF_Units\old\ADFRC_men_dpdu\data\pilotoveralls_DPDU_co.paa"
		};
		weapons[]=
		{
			"ADFRC_usp",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"ADFRC_usp",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"SmokeShellRed",
			"SmokeShellRed",
			"SmokeShellPurple",
			"SmokeShellPurple",
			"ADFRC_f1_grenade",
			"ADFRC_f1_grenade"
		};
		respawnMagazines[]=
		{
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"SmokeShellRed",
			"SmokeShellRed",
			"SmokeShellPurple",
			"SmokeShellPurple",
			"ADFRC_f1_grenade",
			"ADFRC_f1_grenade"
		};
		linkedItems[]=
		{
			"H_PilotHelmetHeli_O",
			"ADFRC_tacticalvest_dpdu",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"H_PilotHelmetHeli_O",
			"V_TacVest_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class ADFRC_teamleader_dpdu: ADFRC_rifleman_dpdu
	{
		author=$STR_ADF_AUTHOR;
		uniformClass="ADFRC_uniform_dpdu";
		model="\A3\characters_F\BLUFOR\b_soldier_03.p3d";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\ADF_Units\old\ADFRC_men_dpdu\data\uniform_DPDU_CO.paa"
		};
		displayName="Brick Leader";
		editorPreview = "\ADF_Units\old\ADFRC_men_dpdu\preview\ADFRC_teamleader_dpdu.jpg";
		weapons[]=
		{
			"ADFRC_WP_M4A5_KAC_EXPS3M",
			"adfrc_usp",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"ADFRC_WP_M4A5_KAC_EXPS3M",
			"adfrc_usp",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"ADFRC_30Rnd_STANAG_mixed",
			"ADFRC_30Rnd_STANAG_mixed",
			"ADFRC_30Rnd_STANAG_mixed",
			"ADFRC_30Rnd_STANAG_mixed",
			"ADFRC_30Rnd_STANAG_mixed",
			"ADFRC_30Rnd_STANAG_mixed",
			"ADFRC_30Rnd_STANAG_mixed",
			"ADFRC_30Rnd_STANAG_mixed",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_f1_grenade",
			"ADFRC_f1_grenade"
		};
		respawnMagazines[]=
		{
			"ADFRC_30Rnd_STANAG_mixed",
			"ADFRC_30Rnd_STANAG_mixed",
			"ADFRC_30Rnd_STANAG_mixed",
			"ADFRC_30Rnd_STANAG_mixed",
			"ADFRC_30Rnd_STANAG_mixed",
			"ADFRC_30Rnd_STANAG_mixed",
			"ADFRC_30Rnd_STANAG_mixed",
			"ADFRC_30Rnd_STANAG_mixed",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_f1_grenade",
			"ADFRC_f1_grenade"
		};
		linkedItems[]=
		{
			"adfrc_ECH_DPDU",
			"ADFRC_PC_Tan_2",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"adfrc_ECH_DPDU",
			"ADFRC_PC_Tan_2",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		icon="iconManLeader";
		backpack="ADFRC_kitbag_tan_GL";
	};
	class ADFRC_squadleader_dpdu: ADFRC_rifleman_dpdu
	{
		author=$STR_ADF_AUTHOR;
		uniformClass="ADFRC_uniform_dpdu_recon";
		model="\A3\characters_F\BLUFOR\b_soldier_03.p3d";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\ADF_Units\old\ADFRC_men_dpdu\data\uniform_DPDU_CO.paa"
		};
		displayName="Section Leader";
		editorPreview = "\ADF_Units\old\ADFRC_men_dpdu\preview\ADFRC_squadleader_dpdu.jpg";
		magazines[]=
		{
			"ADFRC_30Rnd_STANAG_mixed",
			"ADFRC_30Rnd_STANAG_mixed",
			"ADFRC_30Rnd_STANAG_mixed",
			"ADFRC_30Rnd_STANAG_mixed",
			"ADFRC_30Rnd_STANAG_mixed",
			"ADFRC_30Rnd_STANAG_mixed",
			"ADFRC_30Rnd_STANAG_mixed",
			"ADFRC_30Rnd_STANAG_mixed",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_f1_grenade",
			"ADFRC_f1_grenade",
			"SmokeShellRed",
			"SmokeShellRed",
			"SmokeShellPurple",
			"SmokeShellPurple",
			"SmokeShellBlue",
			"SmokeShellBlue"
		};
		respawnMagazines[]=
		{
			"ADFRC_30Rnd_STANAG_mixed",
			"ADFRC_30Rnd_STANAG_mixed",
			"ADFRC_30Rnd_STANAG_mixed",
			"ADFRC_30Rnd_STANAG_mixed",
			"ADFRC_30Rnd_STANAG_mixed",
			"ADFRC_30Rnd_STANAG_mixed",
			"ADFRC_30Rnd_STANAG_mixed",
			"ADFRC_30Rnd_STANAG_mixed",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_f1_grenade",
			"ADFRC_f1_grenade",
			"SmokeShellRed",
			"SmokeShellRed",
			"SmokeShellPurple",
			"SmokeShellPurple",
			"SmokeShellBlue",
			"SmokeShellBlue"
		};
		linkedItems[]=
		{
			"adfrc_ECH_DPDU",
			"ADFRC_PC_Tan_2",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"adfrc_ECH_DPDU",
			"ADFRC_PC_Tan_2",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		icon="iconManLeader";
	};
	class ADFRC_lightGunner_dpdu: ADFRC_rifleman_dpdu
	{
		author=$STR_ADF_AUTHOR;
		uniformClass="ADFRC_uniform_dpdu_recon";
		model="\A3\characters_F\BLUFOR\b_soldier_03.p3d";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\ADF_Units\old\ADFRC_men_dpdu\data\uniform_DPDU_CO.paa"
		};
		displayName="Section Gunner";
		editorPreview = "\ADF_Units\old\ADFRC_men_dpdu\preview\ADFRC_lightGunner_dpdu.jpg";
		weapons[]=
		{
			"ADFRC_minimi_para_elcan",
			"adfrc_usp",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"ADFRC_minimi_para_elcan",
			"adfrc_usp",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"ADFRC_100Rnd_556_Belt_TR5",
			"ADFRC_100Rnd_556_Belt_TR5",
			"ADFRC_100Rnd_556_Belt_TR5",
			"ADFRC_100Rnd_556_Belt_TR5",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_f1_grenade",
			"ADFRC_f1_grenade"
		};
		respawnMagazines[]=
		{
			"ADFRC_100Rnd_556_Belt_TR5",
			"ADFRC_100Rnd_556_Belt_TR5",
			"ADFRC_100Rnd_556_Belt_TR5",
			"ADFRC_100Rnd_556_Belt_TR5",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_f1_grenade",
			"ADFRC_f1_grenade"
		};
		linkedItems[]=
		{
			"adfrc_ECH_DPDU",
			"ADFRC_PC_Tan_7",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"adfrc_ECH_DPDU",
			"ADFRC_PC_Tan_7",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		icon="iconManLeader";
		backpack="ADFRC_kitbag_tan_MG";
	};
	class ADFRC_heavyGunner_dpdu: ADFRC_rifleman_dpdu
	{
		author=$STR_ADF_AUTHOR;
		uniformClass="ADFRC_uniform_dpdu_recon";
		model="\A3\characters_F\BLUFOR\b_soldier_03.p3d";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\ADF_Units\old\ADFRC_men_dpdu\data\uniform_DPDU_CO.paa"
		};
		displayName="Section Gunner (Heavy)";
		editorPreview = "\ADF_Units\old\ADFRC_men_dpdu\preview\ADFRC_heavyGunner_dpdu.jpg";
		weapons[]=
		{
			"ADFRC_maximi_eotech",
			"adfrc_usp",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"ADFRC_maximi_eotech",
			"adfrc_usp",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"ADFRC_100_Rnd_762_Belt_TR5",
			"ADFRC_100_Rnd_762_Belt_TR5",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_f1_grenade",
			"ADFRC_f1_grenade"
		};
		respawnMagazines[]=
		{
			"ADFRC_100_Rnd_762_Belt_TR5",
			"ADFRC_100_Rnd_762_Belt_TR5",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"ADFRC_f1_grenade",
			"ADFRC_f1_grenade"
		};
		linkedItems[]=
		{
			"adfrc_ECH_DPDU",
			"ADFRC_PC_Tan_7",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"adfrc_ECH_DPDU",
			"ADFRC_PC_Tan_7",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		icon="iconManLeader";
		backpack="ADFRC_kitbag_tan_hmg";
	};
	class ADFRC_teeshirt_dpdu: ADFRC_rifleman_dpdu
	{
		scope=1;
		author="$STR_ADF_AUTHOR";
		_generalMacro="ADFRC_marksman_dpcu";
		displayName="Designated Marksman";
		editorPreview = "\ADF_Units\old\ADFRC_men_dpcu\preview\ADFRC_marksman_dpcu.jpg";
		uniformClass="ADFRC_uniform_dpdu_tee";
		model="\A3\characters_F\BLUFOR\b_soldier_02.p3d";
		hiddenSelections[]=
		{
			"Camo",
			"Camo2"
		};
		hiddenSelectionsTextures[]=
		{
			"ADF_Units\old\ADFRC_men_dpdu\data\uniform_DPDU_co.paa",
			"ADF_Units\old\ADFRC_men_dpcu\data\basicbody_army_co.paa"
		};
	};
	class Z_officer_F: I_Soldier_base_F
	{
		model = "\A3\Characters_F_Beta\INDEP\ia_officer.p3d";
		class Wounds
		{
			tex[] = {};
			mat[] = {"A3\Characters_F_Beta\INDEP\Data\officer.rvmat","A3\Characters_F_Beta\INDEP\Data\officer_injury.rvmat","A3\Characters_F_Beta\INDEP\Data\officer_injury.rvmat","A3\Characters_F\Common\Data\basicbody.rvmat","A3\Characters_F\Common\Data\basicbody_injury.rvmat","A3\Characters_F\Common\Data\basicbody_injury.rvmat","a3\characters_f\heads\data\hl_white.rvmat","a3\characters_f\heads\data\hl_white_injury.rvmat","a3\characters_f\heads\data\hl_white_injury.rvmat","A3\Characters_F\Heads\Data\hl_white_bald_muscular.rvmat","A3\Characters_F\Heads\Data\hl_white_bald_muscular_injury.rvmat","A3\Characters_F\Heads\Data\hl_white_bald_muscular_injury.rvmat","A3\Characters_F\Heads\Data\hl_white_02_bald_muscular.rvmat","A3\Characters_F\Heads\Data\hl_white_02_bald_muscular_injury.rvmat","A3\Characters_F\Heads\Data\hl_white_02_bald_muscular_injury.rvmat","A3\Characters_F\Heads\Data\hl_black_bald_muscular.rvmat","A3\Characters_F\Heads\Data\hl_black_bald_muscular_injury.rvmat","A3\Characters_F\Heads\Data\hl_black_bald_muscular_injury.rvmat","A3\Characters_F\Heads\Data\hl_white_hairy_muscular.rvmat","A3\Characters_F\Heads\Data\hl_white_hairy_muscular_injury.rvmat","A3\Characters_F\Heads\Data\hl_white_hairy_muscular_injury.rvmat","A3\Characters_F\Heads\Data\hl_white_old.rvmat","A3\Characters_F\Heads\Data\hl_white_old_injury.rvmat","A3\Characters_F\Heads\Data\hl_white_old_injury.rvmat","A3\Characters_F\Heads\Data\hl_asian_bald_muscular.rvmat","A3\Characters_F\Heads\Data\hl_asian_bald_muscular_injury.rvmat","A3\Characters_F\Heads\Data\hl_asian_bald_muscular_injury.rvmat","A3\Characters_F_Exp\Heads\Data\hl_tanoan_bald_muscular.rvmat","A3\Characters_F_Exp\Heads\Data\hl_tanoan_bald_muscular_injury.rvmat","A3\Characters_F_Exp\Heads\Data\hl_tanoan_bald_muscular_injury.rvmat","A3\Characters_F_Exp\Heads\Data\hl_asian_02_bald_muscular.rvmat","A3\Characters_F_Exp\Heads\Data\hl_asian_02_bald_muscular_injury.rvmat","A3\Characters_F_Exp\Heads\Data\hl_asian_02_bald_muscular_injury.rvmat"};
		};
		hiddenSelections[] = {"camo1","camo2"};
		hiddenSelectionsTextures[] = {"\ADF_Units\old\ADFRC_men_dpdu\data\uniform_field_DPDU_CO.paa","\ADF_Units\old\ADFRC_men_dpdu\data\uniform_field2_DPDU_CO.paa"};
		uniformClass = "ADFRC_uniform_field_DPDU";
		scope = 2;
		displayName = "field";
	};
};
class cfgWeapons
{
	class ItemCore;
	class HeadGearItem;
	class UniformItem;
	class ItemInfo;
	class Uniform_Base;
	class Vest_Camo_Base;
	class VestItem;
	class U_B_CombatUniform_mcam;
	class U_I_OfficerUniform;
	class ADFRC_uniform_dpdu: U_B_CombatUniform_mcam
	{
		scope=2;
		author=$STR_ADF_AUTHOR;
		displayName="Disruptive Pattern Desert Uniform (Long Sleeve)";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\ADF_Units\old\ADFRC_men_dpdu\data\uniform_DPDU_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="ADFRC_rifleman_dpdu";
			containerClass="Supply20";
			mass=80;
		};
	};
	class ADFRC_uniform_dpdu_medic: ADFRC_uniform_dpdu
	{
		scope=2;
		author=$STR_ADF_AUTHOR;
		displayName="Disruptive Pattern Desert Uniform (Medic)";
		hiddenSelectionsTextures[]=
		{
			"\ADF_Units\old\ADFRC_men_dpdu\data\uniform_DPDU_MEDIC_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="ADFRC_medic_dpdu";
			containerClass="Supply20";
			mass=80;
		};
	};
	class ADFRC_uniform_dpdu_recon: ADFRC_uniform_dpdu
	{
		scope=2;
		author=$STR_ADF_AUTHOR;
		displayName="Disruptive Pattern Desert Uniform (Short Sleeve)";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\ADF_Units\old\ADFRC_men_dpdu\data\uniform_DPDU_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="ADFRC_teamLeader_dpdu";
			containerClass="Supply20";
			mass=80;
		};
	};
	class ADFRC_uniform_field_DPDU: Uniform_Base
	{
		author=$STR_ADF_AUTHOR;
		scope = 2;
		displayName = "Disruptive Pattern Desert Field Dress";
		model = "\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[] = {"camo1","camo2"};
		hiddenSelectionsTextures[] = {"\ADF_Units\old\ADFRC_men_dpdu\data\uniform_field_DPDU_CO.paa","\ADF_Units\old\ADFRC_men_dpdu\data\uniform_field2_DPDU_CO.paa"};
		class ItemInfo: UniformItem
		{
			uniformModel = "-";
			uniformClass = "Z_officer_F";
			containerClass = "Supply40";
			mass = 40;
		};
	};
	class U_B_PilotCoveralls;
	class ADFRC_uniform_dpdu_pilot: U_B_PilotCoveralls
	{
		scope=2;
		author=$STR_ADF_AUTHOR;
		displayName="Army Aviation Coveralls (DPDU)";
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="ADFRC_helicopterPilot_dpdu";
			containerClass="Supply20";
			mass=20;
		};
	};
	class ADFRC_uniform_dpdu_tee: ADFRC_uniform_dpdu
	{
		scope=2;
		author="$STR_ADF_AUTHOR";
		displayName="Disruptive Pattern Desert Uniform (Tee)";
		picture="";
		model="\A3\characters_F\BLUFOR\b_soldier_02.p3d";
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="ADFRC_teeshirt_dpdu";
			containerClass="Supply20";
			mass=80;
		};
	};
};
